### ISSUE TITLE
Crash on Database->Transaction mode navigation with PostgreSQL

### ISSUE THREAD

**Issue by efulmo** [serge-rider/dbeaver#100]
I have stt up the connection to PostgreSQL. When I go to Database->Transaction menu, DBeaver window closes immediately.

Ubuntu 14.04 LTS.
Package: dbeaver-ce-3.5.6-linux.gtk.x86_64.tar.gz.

**Comment by serge-rider** [comment]
Can't reproduce.
Are there any log files? Usually thread dump remains somewhere (current dir?). It should have name like hs_err_<pid>.log.

**Comment by efulmo** [comment]
Found this one in my home directory:
[hs_err_pid5218.log.txt](https://github.com/serge-rider/dbeaver/files/58160/hs_err_pid5218.log.txt)

**Comment by serge-rider** [comment]
Thanks.
It is a GTK (Unity) related issue: https://bugs.eclipse.org/bugs/show_bug.cgi?id=419729
See the most recent comments. Possible workaround: 
```
export SWT_GTK3=0
export UBUNTU_MENUPROXY=0
```
But I can't confirm this is working because I still can't reproduce it in my test environment (it is reproducible on Ubuntu 14.04 and Ubuntu 13 - but not on the recent Ubuntu).
