### ISSUE TITLE
'Refresh default object' after running a sql

### ISSUE THREAD

**Issue by ray3888** [serge-rider/dbeaver#1071]
noticed that there is 'Refresh default object' action after running a sql, and it may take some time if db is slow. what's the purpose of it? is there option to switch off? is it possible to block running other sql during 'Refresh default object' ?
the problem is that for some db(like hive) not support running multi sql at same time will cause exception and need to close dbeaver and reopen it. 
thanks.

**Comment by serge-rider** [comment]
There is no such option now, I'll add one in the next version.
Also I'll change def object update so it will use metadata connection (instead of current SQL editor connection) so it won't block query execution.
BTW "Refresh default object" actions supposed to work very fast. I wondering why it works so slow in Hive.

**Comment by serge-rider** [comment]
![image](https://cloud.githubusercontent.com/assets/6398845/21258523/6ecfe1be-c38e-11e6-8086-a55dac24c5dc.png)

**Comment by ray3888** [comment]
thanks @serge-rider , we use spark thrift server to query hive, usually is fast to refresh default object, but quite slow when all executors are occupied. also depend on network.
