### ISSUE TITLE
Feature Request: Show column comments in MetaData Viewer and as an option below grid column name

### ISSUE THREAD

**Issue by xantari** [serge-rider/dbeaver#1105]
Within the MetaData panel you can see a lot of information about the columns in the table.

however the thing that is missing is the column description information.

The column description information is only available by hovering over the column names, which then show it within a tooltip.

I would much rather have it show up in the meta data panel, which I can move to my other monitor or show up beside the results so I know what I am viewing.

Additionally if possible, it would be awesome if there was a way it could show up underneath the column in the grid panel, which would help those who like to see it directly next to the data they are viewing (better UI experience). Actually both in the grid and the Metadata panel would be ideal, so people can do it anyway they wish.

FYI, this is very useful for legacy databases which have very cryptic column names that are limited to 8-10 characters (depending on database type, such as IBM i DB2 / AS400 databases). Often times the programmers put in better info on what the column meant in the column description fields since they were so limited in column names.

**Comment by xantari** [comment]
FYI, this is very useful for legacy databases which have very cryptic column names that are limited to 8-10 characters (depending on database type, such as IBM i DB2 / AS400 databases). Often times the programmers put in better info on what the column meant in the column description fields since they were so limited in column names.

**Comment by serge-rider** [comment]
Well, I got the point but that's not so easy.

Metadata panel shows metadata of current SQL statement - exactly as it returned by driver (even if you are viewing table contents - it is a result of `SELECT * FROM table` query).
The problem is - column description is not returned along with other column properties. It is a limitation of JDBC API (and most of other database APIs) - just because it is redundant in most cases.
Column description can be obtained only during table metadata extraction.

Possible solution: I can show column descriptions (if they are known) in grid header on the second line. Like this:

| CRAZYNAME<br/>good name | MADNESS<br/>rational name |
-----------|-------------|
|value | value
|value | value
|value | value

Of course this should be configurable.
The problem I see - how to handle long descriptions. They can be very long, even multiline.

Another solution (or workaround) - I still can push column description in metadata panel (this will be a kind of hack but I can go this way if there are no other options).

**Comment by xantari** [comment]
Both options are fine with me. Just as long as I don't have to hover over every column to figure out what it is (which is what I do now). I do see that long descriptions may pose a problem, with our DB2 database I believe the limit is 105 characters in length. I believe in MS SQL you are allowed much longer lengths. Which is why it probably is important to have it available in both places and folks can either turn it on in both the column/grid view, or only show it in the metadata panel view. Metadata panel would would be preferable for very long descriptions as it shows as a row based display which can be moved to another monitor if needed.

**Comment by xantari** [comment]
Also, this information must already be pulled as they are in the tooltip, so i'm guessing it just needs to be addeed to the grid as a second row.

FYI, this feature is in SQL Workbench/J, which is open source. They have a different way of showing the metadata panel than DBeaver.

Honestly the interface in DBeaver is better, and intellisense works better as well. So if this feature gets added it would definately be my goto SQL Editor as everything about DBeaver is easier to use. And unfortunately IBM's Data Studio and their IBM i specific SQL Editor is light years behind what DBeaver offers.

**Comment by serge-rider** [comment]
Optional descriptions in grid header will be added in 3.8.3.
Please provide some feedback.

![default](https://cloud.githubusercontent.com/assets/6398845/21752505/808948f0-d5ea-11e6-9ae2-1d27b406397e.png)

**Comment by xantari** [comment]
Just tried this out. AWESOME! Thanks so much for adding it.

**Comment by serge-rider** [comment]
Changing metadata panel is quite complicated (panel meta model has to be refactored). Let's consider this task as done with just grid header improvement.

You can create separate issue for just metadata panel. There could be some other improvements besides description column.

**Comment by colderleo** [comment]
This option is quite hard to find, and I think it would be much convenient to add it to right click menu.

**Comment by DavidHJong** [comment]
really hard to find this option. 
it's in windows > preferences > editors > data editor > appearance > show column description in header.
