### ISSUE TITLE
Statement delimiter problem with BEGIN; keyword

### ISSUE THREAD

**Issue by ced75** [serge-rider/dbeaver#1114]
Hi,

DBeaver 3.8.2 on Linux Mint 64 bits
PostgreSQL 9.6

I create a SQL script which begins with BEGIN; to begin a transaction and finishes with COMMIT; to validate the transaction.

If I put the cursor on the BEGIN; line and perform a Execute statement, the BEGIN; line is processed with all the code until the COMMIT.
What I expected was that only the BEGIN; statement to be performed.

Is it a "normal" feature? If it is, is it possible to add an option to deactivate it (in order to only process the BEGIN line)?

Thanks in advance.
Regards,

Cedric

**Comment by hexpunK** [comment]
I've experienced this myself as well.

Usually when running any statements in DBeaver, the software will only run until the first delimiting semi-colon. However, twice in this week alone I've managed to fudge some data (fixable data thankfully) while trying to use the `BEGIN` keyword in a similar fashion. When doing so the entire script in the editor is run for me, rather than just the `BEGIN.`

I'm almost certain that this used to behave in line with every other statement I run, it's apparently been a problem since I upgraded to 3.8.2 (running on OS X Sierra).

Has this been resolved as of version 3.8.3 by any chance?

(also @ced75 may I suggest sticking the "bug" label on this issue? it may make it easier for the developer to prioritise!)

**Comment by serge-rider** [comment]
Since one of the recent versions DBeaver processes whole BEGIN/END block as a single statement. It also includes DECLARE block (which may come before BEGIN).
This is a feature.

What's the point of executing just BEGIN clause? It does nothing.
Anyhow you can execute it by selecting BEGIN keyword + Ctrl-Enter.

**Comment by hexpunK** [comment]
I largely execute the BEGIN by itself just to get myself into a transaction. I usually want to perform multiple actions separately when manually working with data, so I can verify my changes are doing what I expect in the middle of the transaction.

I can understand why making it execute the entire block makes sense however. I just don't remember seeing anything mentioning it in a changelog (it could very well be there, I don't have a great memory!) so it was a bit of a shock and felt unintended when I first got caught by it.

I'll keep that in mind for the future however.
Thanks for the response!

**Comment by ced75** [comment]
Hi Serge,

Start a transaction in PostgreSQL with "BEGIN" is possible because "BEGIN" is a shortcut for "BEGIN TRANSACTION".
I'm used to starting transactions with just "BEGIN" because I'm lazy and I have fewer letters to type.

I had found the solution based on selecting the whole BEGIN word and execute the statement.
Could it be possible to add, in the auto-complete list, "BEGIN TRANSACTION" when typing "BEG..." ?
Thanks again.

**Comment by serge-rider** [comment]
I see.

Currently DBeaver thinks that BEGIN is a start of new SQL block (and looks for corresponding END operator).
But PostgreSQL doesn't use BEGIN/END blocks in regular SQL. They are needed only in functions and PL/pgSQL. So I can just disable this for PostgreSQL.

**Comment by serge-rider** [comment]
Workaround in current version: use START TRANSACTION instead of BEGIN.

**Comment by ced75** [comment]
That would be great.
Thanks a lot.
