### ISSUE TITLE
mysql column set/view date column value

### ISSUE THREAD

**Issue by SergeySmile** [serge-rider/dbeaver#1127]
Hello. It is a problem with '0000-00-00' values in date columns

1) It displays as NULL:
![](https://d1ro8r1rbfn3jf.cloudfront.net/ms_130224/DjD83UG3YuZ9YoElvwKCDHilaHGvhD/DBeaver%2BEnterprise%2B-%2BGeneral%2B-%2B%255B%2Bprojects%2B%255D%2B2017-01-06%2B21-39-10f54z1vut29o6cvdpws46j1dxc.png?Expires=1483817965&Signature=ErhqpdcuHIHA6TgEgUCiq7kiCJ5019nSqMff5HNkN4Y~E7yjKGnp4JZ1ipJBbxcSGWk2ay7mcTwhGB5P8fQjhPhqGxq-wi~w4FrOsGUr5SAUhHLhWPwlhAiSEBZ867vEOi68jByVGAwt55qpFUfHjVYU2iRqS~LzcXsG2n7-dP~hOVg1ctOTz33e05~7oWz0LOLtku5XBftRkoyIOaCE1ETEksqwbhX5pG8Xeptv6~d9fbIYhBdlzP-A4I3dfAz8eQOjJ6m8G~lZV~sU~67duJ1REkFd2Vf5DwRRbkvgRdEDJ8BPupjQ3CiCg9j8eGEDIaWkKkWIFfMtH54XRu7tug__&Key-Pair-Id=APKAJHEJJBIZWFB73RSA)
2) When i try to set '0000-00-00' value for date column - after save value converts to 0002-11-30
![](https://api.monosnap.com/rpc/file/download?id=lCOwRjsfZyk0r8C8iB09wcZllzFqqe)

I tried to solve it by data format settings - but nothing help.

**Comment by theonedemon** [comment]
+1 mush have this fix!

**Comment by serge-rider** [comment]
You can control MySQL zero time values presentation by changing connection driver property "zeroDateTimeBehavior".

The problem is that date value '0000-00-00' is not valid and can't be represented as a date or a timestamp. By default it is represented as NULL. You can set zeroDateTimeBehavior to 'round' but this will convert zero into valid '0001-01-01' date value (which is obviously not what you need).

MySQL JDBC driver just not capable to handle zero time values. I can add some special MySQL handler to allow adding new zero values but I can't read existing values from database. This is driver limitation.

**Comment by SergeySmile** [comment]
Okay. I understand why does it works like now.
> I can add some special MySQL handler to allow adding new zero values but I can't read existing values from database.

Special MySQL handler to allow adding new zero values will be enough and make me and my frineds more comfortable with dbeaver. Because now i execute common sql query for setting zero date and it is so sad(

P.S Thanks for feedback and great database manager.
P.P.S Hope to see handler in incoming releases ^^

**Comment by serge-rider** [comment]
Ok. That's easy.

**Comment by sirtet** [comment]
@serge-rider, when u say "Limitation of the driver", what kind of driver is that?
Are there no other drivers available?
How do other tools like HeidiSQL get around this?

**Comment by chuck-wood** [comment]
> How do other tools like HeidiSQL get around this?

And MySQL's own CLI client!

**Comment by p91paul** [comment]
HeidiSQL is written in Delphi, and the MySQL CLI possibly in C (this one is just wild guess). Dbeaver uses JDBC driver because that's what Java supports. Despite being all official drivers, drivers for different languages might have different features/bugs.
