### ISSUE TITLE
DBeaver EE license and further project changes

### ISSUE THREAD

**Issue by osrojas** [serge-rider/dbeaver#1145]
Hi,

Where would I find the license terms for DBeaver Enterprise Edition since it's considered freeware and does not fall under the GPL 2 open-source license that the Community Edition does?

Thanks,
Ogden

**Comment by serge-rider** [comment]
Glad that you asked - this is a popular question (mostly in emails).
We are going to make major changes in licensing and add commercial support and other stuff in near future (month +/-).
I'll use this topic as a reference for current transition period.

### 1. What is the difference between CE and EE?
EE version is based on CE. Additionally it contains a few extra plugins (NoSQL suport, persistent query manager and a few others). So, EE = CE + extra plugins.

### 2. How to buy EE version?
Nohow. Currently EE version is as free as CE.
Also there is no commercial support for EE - just because jkiss.org isn't a commercial company.

### 3. What is EE version license terms?
There is no such thing. Currently CE version is licensed under GPL 2 while EE is just freeware. Additional EE plugins aren't open source and are not linked to any particular OS/proprietary license.
As said on the "About" page: 
DBeaver is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
That's it.

### 4. What will change?
#### 4.1 CE version
I'm going to liberate the license. GPL is too restrictive so I'm going to change it on Apache or Eclipse license. Final decision will be made in the following couple of weeks.
If you have any thoughts about better OS license - please write comments here.
Moving from GPL means that DBeaver can't use GPL libraries anymore. Good news is: it doesn't use them already. All dependencies are licensed under Eclipse, Apache, or LGPL (as far as I know - please correct me if I'm wrong).

Important statements:
- CE version will be open-source and free forever. There are no plans to make it commercial (sell it for money).
- CE version won't contain any artificial limitations and/or functionality cuts to make users to move to EE version.
- CE version will continue to develop as it is a base for EE version. Most of new features will be added to CE version while EE will remain just more "enterprise-friendly" version of CE.

#### 4.2 EE version
EE version will become commercial (starting from version 4).
I can't support this project (which eventually became huge and takes too much of my time) for free. There are too many expenses already.
Some proprietary license terms will be applied to EE version (something pretty standard).

EE version will have commercial support.
Initially it is planned to sell EE version license for some reasonable amount of money (not yet decided). It will be a perpetual license with one year of free version upgrade + one year of support.
There will be a trial license (2-4 weeks) + free license for educational purposes (universities, etc).
Maybe there will be some ultimate support program (more expensive).

EE version will be released less often than CE, maybe once per quarter (because it has to be more stable/tested).

EE binaries will be signed with official code-sign certificates (this will automatically solve many problems with installations on Mac and Windows).

### 5. What about other contributors?
Besides me there is a bunch of people who made contributions to DBeaver CE. You can see the list of major contributors here: http://dbeaver.jkiss.org/about/. And you can see others in pull requests history in this GitHub repository.
All these contributions were made under GPL license which is supposed to be changed to a more commercial-friendly OS license (see above). So there may be some kind of conflict fo interests.
All contributors have to agree with this change otherwise their contributions have to be removed from DBeaver codebase.
All this will be discussed with each and every contributor (if this is technically possible). Everyone has to be happy about these new changes.

### 6. Still have questions?
Please ask any questions, make your advices, share thoughts etc right in this topic. Or write me on serge@jkiss.org.

**Comment by osrojas** [comment]
Great response. Thank you!

**Comment by osrojas** [comment]
Hi Serge,

As version 4.0 is about a month away, would you be able to provide an estimated price range for the Enterprise Edition? My company is looking at several options and price is a huge factor.

Thanks,
Ogden

**Comment by serge-rider** [comment]
It won't be expensive.
Price range for 1 perpetual license + 1 year of free version upgrade + 1 year of online support will be 50-100 USD.

Also there may be some kind of premium support option and some discounts.

This is not like I'm selling DBeaver to some greedy enterprise shark. The whole idea is to let me to focus on DBeaver development/support.

**Comment by osrojas** [comment]
Wonderful, thank you.

**Comment by osrojas** [comment]
Could you give an update on what's in store and timelines for the Enterprise Edition of DBeaver?

**Comment by serge-rider** [comment]
EE version release was postponed. 
Now the plan is to release it in June-July 2017.

**Comment by serge-rider** [comment]
Check this topic: https://github.com/serge-rider/dbeaver/wiki/Enterprise-Edition
(hint - there is a small gift for community)
