### ISSUE TITLE
[Feature] Oracle: Add/Edit/Delete scheduler jobs / dbms jobs

### ISSUE THREAD

**Issue by moonwhaler** [serge-rider/dbeaver#1165]
In SQL Developer I am able to add/edit/delete database scheduled jobs. It would be great to get this feature in DBeaver, too.

![2017-01-20 10_10_00-oracle sql developer _ metapack-ol](https://cloud.githubusercontent.com/assets/1736467/22142982/a6b77cf6-def8-11e6-82b7-b7a0fce5cd57.png)

![2017-01-20 10_11_43-oracle sql developer _ schnewjob xpack delete_double_imported_entries metapack-o](https://cloud.githubusercontent.com/assets/1736467/22143077/0825c61e-def9-11e6-9999-dab359ecec12.png)

**Comment by serge-rider** [comment]
First scheduler metadata version will include jobs and programs in read-only mode.

Honestly I'm not an expert in this area so I can't make good UI on my own just because I'm not familiar with use-cases.
It'd be good if someone will describe good UI for scheduled jibs/programs/etc (as a separate feature request).

**Comment by moonwhaler** [comment]
If you like, you may have a look at the Oracle SQL Developer for further insight. That's where I got the screenshots from and it's solved in a very consistent manner, I think.

**Comment by serge-rider** [comment]
I have SQL developer and can see this. But I don't want to just replicate all functions. This requires a lot of effort and I'm not sure that SQL developer has the best UI/behavior (usually it doesn't).

So you can create feature request with desired UI for some particular features related to scheduled jobs.
