### ISSUE TITLE
Copy and paste of table data 

### ISSUE THREAD

**Issue by elring** [serge-rider/dbeaver#1178]
I try to duplicate record in table (data) editor. I click "Copy" (or Advanced Copy) to put data in clipboard. Then I "Add new row" and try to paste the data via "Advanced Paste" (which seems to paste multiple fields). 

Everything is ok, except when some fields contains special characters like tabs or newlines. These characters are field/record separators so everything is mixed up. I think text data (or all data) should be quoted when copying to clipboard and parsed by quotes when pasted from clipboard (at least in Advanced Copy/Paste mode).

I tried all 3 options in Advanced Copy with no luck. Another problem is that "Database native" format does't copy data at all.

**Comment by serge-rider** [comment]
I can just copy a row (a toolbar button right next to the New Row).

**Comment by elring** [comment]
Thanks for hint. Button "Copy current row" works. Could be added in context menu (right click) - "Delete" is here, so maybe add items "Add new row" and "Duplicate current row" (because Copy current row could be misleading - no clipboard involved here).

Original issue with copy & paste remains (need to quote text when copying text data with \t and \n and advanced copy format "Database native" not working).

**Comment by serge-rider** [comment]
Agreed with "Duplicate" instead of "Copy". Will change it.

But I don't want to add extra items in context menu - it is a bit heavy already. You can use shortcuts (alt+insert and ctrl+alt+insert).

I don't know how to resolve problems with \t and \n in advanced paste. 

Main idea of delimiting cells with tabs and linefeeds was to provide ability to paste it into Excel (or Calc) spreadsheet. There is no standard way to quote cell values (or at least I don't know about it).
Moreover you can copy cells from Excel into DBeaver - and Excel doesn't quote cell values.

**Comment by elring** [comment]
I undestand the reason - export to Excel. But both LibreOffice Calc and MS Excel (at least 2013) understands quoted clipboard. 

Try to paste this text to Excel and Calc:
````
col1	col2	col3
"long col 1 with
multiple
lines"	"long col2 with multiple tabs here	and	here"	"sdadsasdadsa"
````

**Comment by serge-rider** [comment]
Agreed, this makes sense. At least this will work in one direction.
