### ISSUE TITLE
Cannot close connection after lost VPN conn.

### ISSUE THREAD

**Issue by acsdev** [serge-rider/dbeaver#1185]
I need to work connected an VPN network everytime. Sometimes - for many reasons - that connction breaks.
When that happens, the function "Disconnect " does not work anymore, beside that, if I try used it, dbeaver stops to work and I have to kill and restart it over to continue work.

**Comment by iron0012** [comment]
I have noticed this as well. Although "Disconnect" after connection has already been lost while connected through a VPN causes  DBeaver to hang (spinning beach ball on a Mac), if I continue to wait, after about 2 full minutes the problem resolves itself and DBeaver continues to function normally.

**Comment by acsdev** [comment]
I have this issue on Linux (Mint Rosa), and it never resolves by itself. 
Sometimes DBeaver stay completely frozes after I try to use "Disconnect" function.

**Comment by serge-rider** [comment]
This is a known problem. If socket timeout was set in driver properties then you'll have to wait this amount of time until connection will be lost. Otherwise you may wait forever (because no timeout will ever happen).

I can't affect driver connection timeout but I can improve disconnect action so it will wait for some time (e.g. 5-10 seconds) and then finish (without real socket close).
