### ISSUE TITLE
Bug: High CPU Usage & Freezing with autocomplete on 3.8.4 not 3.8.3

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#1189]
Hey Serge,

Downloaded 3.8.4 today and ended up rolling back as there appears to be some sort of bug with autocomplete. 

Whenever i try and complete and autocomplete something in an editor window that has another statement the cpu use goes very high. (3-4x 3.8.3) and hangs for a minute before it comes back with results. I first noticed this on Teradata but was able to reproduce it on mysql as well.

Note I was going to try and come up with a test case to help you reproduce as was wondering if you use/have a test database for these kinds of test? (somewhere that you could base unit tests off).

**Comment by r-richmond** [comment]
my sql editor window looks something like this although i've changed the names of the schemas/columns

```
select
  bd.`DATE` as "week",
  bd.region,
  bd.value1,
  bd.longname,
  bd.cool_name,
  bd.forgotten_name,
  bd.column_name,
  coalesce(cd.fancy_name, 0) as "fancy_name",
  coalesce(sd.old_name, 0) as "old_name",
  coalesce(sd.metric, 0) as "metric"
from schema_01.table1 as bd -- base data
left join schema_01.table2 as cd -- churn data
  on adddate(bd.`DATE`,6) = cd.week
 and bd.region = cd.region
left join schema_01.table3 as sd -- session data
  on adddate(bd.`DATE`,6) = sd.week
 and bd.region = sd.region
 
select *
from schema_01.table1 as bd

SELECT `t`.`date`, SUM(t.cool) 
FROM schema_01.`table1` AS `t` 
GROUP BY `t`.`date` 
ORDER BY `t`.`date` desc

select
  i. -- if i press auto complete (ctrl-space) after the i. bad things happen in 3.8.4 not 3.8.3
from new_schema.table_10 as j
join new_schema.table_20 as i
  on i. -- if i press auto complete (ctrl-space) after the i bad things happen in 3.8.4 not 3.8.3
```

**Comment by serge-rider** [comment]
Once UI will freeze please make a thread dump and then post it here.

Probably this is caused by recent changes in completion processor. Although I can't reproduce it.

**Comment by r-richmond** [comment]
Attached dump [thread-dump.txt](https://github.com/serge-rider/dbeaver/files/730942/thread-dump.txt)

p.s. is there a way to propose changes to the wiki?

for mac I had to run

```
ps -A | grep -m1 dbeaver | awk '{print $1}'
jstack 10387 > ~/Desktop/thread-dump.txt
```

**Comment by serge-rider** [comment]
Yes, this is a result of recent SQL completion fix. Regex evaluation works too long on your machine (I can't say why - although it is quite complex regex it works really fast (less than a second for big queries) on my test machines. No matter how complex SQL query is. Maybe regex implementation in Mac Java is just slow.
Anyhow, I'll try to simplify this. Thanks for report.

PS I've fixed wiki, thanks for info.

**Comment by carlosspohr** [comment]
Serge,

I also got this here, all dev workstations have the same problem on 3.8.4,
even after we did a cleaning on workspace.

I'll provide you a dump tomorrow by morning.

For now, we did a downgrade to 3.8.3.

PS:

1- Early after open dbeaver, it's keeps CPU close to 25%, then, after some
query execution, it freezes.

2- with both open, eclipse and dbeaver, and, I'm coding on eclipse,
sometimes that autocomplete window throws in front of eclipse's windows
stealing focus to it.

3- all tested PCs are using Windows 10 x64 and up-to-date.

On Jan 25, 2017 7:47 PM, "Serge Rider" <notifications@github.com> wrote:

Yes, this is a result of recent SQL completion fix. Regex evaluation works
too long on your machine (I can't say why - although it is quite complex
regex it works really fast (less than a second for big queries) on my test
machines. No matter how complex SQL query is. Maybe regex implementation in
Mac Java is just slow.
Anyhow, I'll try to simplify this. Thanks for report.

PS I've fixed wiki, thanks for info.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/serge-rider/dbeaver/issues/1189#issuecomment-275242971>,
or mute the thread

**Comment by r-richmond** [comment]
I think @carlosspohr has already said this but just to be explicit. I was able to reproduce this on a coworkers windows-10 machine.

**Comment by serge-rider** [comment]
Yep. Performance problems comes from slow auto-completion. It supposed to be very fast but something went wrong..

**Comment by serge-rider** [comment]
I made a quick fix, you can check it in EA version: http://dbeaver.jkiss.org/files/ea/
Please report whether it fixes performance issue. Also please check that auto-completion still works ok.

**Comment by carlosspohr** [comment]
Thanks, Serge. I'll test it.

**Comment by carlosspohr** [comment]
@serge-rider, I tested it here and seems all working fine. No more freezing or high cpu usage after some query executed.

Thanks!

**Comment by r-richmond** [comment]
@serge-rider I can confirm @carlosspohr results. The issue is resolved for me as well. Thanks for the amazing turn around time.

**Comment by serge-rider** [comment]
Ok, thanks.
I will probably release hotfix version on the next week..
