### ISSUE TITLE
MongoDB - Impossible to connect without admin privileges 

### ISSUE THREAD

**Issue by codebling** [serge-rider/dbeaver#121]
On connect, DBeaver executes a `show dbs` request in the form of either `db.adminCommand('listDatabases')` or `db.getMongo().getDBNames()`, but both of these require admin privileges, which results in the connection attempt failing.

**Comment by serge-rider** [comment]
Thanks for report! That was very helpful. I knew there were problems with authentication in Mongo but I didn't realize that's because of admin commands.

**Comment by codebling** [comment]
No, thank you!  I am seeing a lot of discrepancies with the Mongo behaviour versus other connections, so far I have only filed the major ones, is it helpful if I file the others as well? (and is this the right spot to be filing them)

**Comment by serge-rider** [comment]
It will be helpful, definitely.

But it doesn't make sense to report minor issues because that'll distract
from serious problems.
Mongo and Cassandra extensions are poorly tested. There should be many
major issues.
Last months I'm not using none of them in my daytime job so they looks a
bit abandoned.

2015-12-18 0:07 GMT+03:00 codebling <notifications@github.com>:

> No, thank you! I am seeing a lot of discrepancies with the Mongo behaviour
> versus other connections, so far I have only filed the major ones, is it
> helpful if I file the others as well? (and is this the right spot to be
> filing them)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/serge-rider/dbeaver/issues/121#issuecomment-165582342>
> .
>



-- 
Thanks,
Serge Rieder

mail: serge@jkiss.org
web: http://jkiss.org

**Comment by codebling** [comment]
That's what I figured. Mongo seems useable but is definitely lacking a lot functionality compared with the SQL connections supported by DBeaver, so a lot of the things I'm noticing fall in the grey area between issues and features. I will file them here and in the worse case these issues can be closed as "won't fix".
