### ISSUE TITLE
Question/Request: Dot File Support

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#1210]
Hey Serge,

I'm currently storing some of my Dbeaver settings in my [repo](https://github.com/r-richmond/dotfiles_rr/tree/master/.dbeaver/.metadata/.plugins/org.eclipse.core.runtime/.settings) and am wondering if this is the best way to store some of these settings?  (Mainly I'm worried about a future update breaking my hacky solution)

Also I was wondering if you could point me to where I could find the file that stores templates as I would like to add those as well.

**Comment by serge-rider** [comment]
Not sure that this is the best way - however this will work in future. I don't have plans to change DBeaver preferences model.

Although DBeaver 4.x will keep workspace in `~/.dbeaver4` instead of `~/.dbeaver` (workspace migration procedure will be included). At least that's the plan.

Templates reside in `.plugins/org.jkiss.dbeaver.core/templates.xml`.

**Comment by r-richmond** [comment]
Ok Thanks for info.
