### ISSUE TITLE
Allow user to set time zone

### ISSUE THREAD

**Issue by jonas-hagen** [serge-rider/dbeaver#1224]
DBeaver seems to display all timestamps in local time. When I export TZ='UTC' before starting DBeaver, the timestamps are displayed in UTC. But there seems not to be an appropriate setting in the Preferences dialog.

The user should be able to choose the time zone or use the one of the server. Also it would be nice if the timestamp format would be "yyyy-MM-dd HH:mm:ss z" by default (with "z" for time zone) or the time zone could be displayed in the status bar.

(I am using PostgreSQL 9.5 and DBeaver 3.8.1.)

**Comment by serge-rider** [comment]
Timezones handling is very database-specific. Many drivers just ignore client timezone. 
So this issue is PostgreSQL specific.
To set client timezone you can export TZ (on Linux) or run DBeaver with parameter: `dbeaver -vmargs -Duser.timezone=UTC`.

No sure about default timestamp format. Most people don't care about timezones (shame on them) so it'll be too verbose.

Showing current timezone (and also current locale and default files charset) in status bar might be a good idea.

**Comment by jonas-hagen** [comment]
Thanks for the hint with the command line arguments!

I suspect the display elements (the table cells) to adapt to the local time zone. The server is set to UTC and connection default also is UTC. It took me quite a while to find out what was going on, because I assumed that DBeaver would also display in UTC in this case.

**Comment by hbarcelos** [comment]
I had the same issue, but the suggested fix didn't work.

So I dug a little deeper and found this [issue](https://github.com/dbeaver/dbeaver/issues/1559).
Since I'm using Java 10, I had to use:

```
dbeaver -vmargs --add-modules=java.se.ee -Duser.timezone=UTC
```

For Linux environments, if you want the desktop entries to use this by default, you have to change the **one** of the following files, depending on your distro and how you installed it:

- `/usr/share/applications/dbeaver.desktop`
- `/usr/local/share/applications/dbeaver.desktop`
- `~/.local/share/applications/dbeaver.desktop`

```diff
 [Desktop Entry]
 Name=DBeaver
 GenericName=Free universal SQL Client for developers and database administrators
-Exec=dbeaver
+Exec=dbeaver -vmargs --add-modules=java.se.ee -Duser.timezone=UTC
 Terminal=false
 Type=Application
 Icon=dbeaver
 Categories=Development;Java;Database;
 StartupWMClass=SWT
```

**Comment by serge-rider** [comment]
@hbarcelos I'd suggest to add this parameter in dbeaver.ini file rather than in .desktop. Otherwise you will have to duplicate all properties specified in dbeaver.ini by default.

**Comment by hbarcelos** [comment]
Thank's a lot @serge-rider, that's even better!

**Comment by ajmichels** [comment]
Why can't it just output dates as they are defined in the data? This seems like a huge flaw in this tool. Changing dates without asking you if you want to do that can create huge problems. Even setting this argument to UTC doesn't do what you would expect, it is still potentially going to convert data coming out of your database to a different time.

**Comment by emesterhazy** [comment]
## FYI in case it isn't clear:

This is fixed in the current version and available through a setting here:

![Properties > Data formats > use native date/time format](https://user-images.githubusercontent.com/6398845/46403801-2a6b2500-c70c-11e8-9309-d58187a2d818.png)

**Comment by ajmichels** [comment]
Great. Thank you. Glad to hear this feature is now available. 

I guess I will have do a clean install. Every time I have tried to use the "Check for Updates" feature in the past 6 months I have gotten a null pointer exception.

**Comment by alex88** [comment]
@emesterhazy is it actually fixed with that? What I see is the same time as my current timezone just with `-07:00` added at the end, so I'm not actually seeing the UTC times as with adding the parameter

**Comment by rvangsgaard** [comment]
For internet searchers using the Flatpak version of DBeaver, set time zone with this command:
`flatpak run io.dbeaver.DBeaverCommunity -vmargs -Duser.timezone=UTC`

Replace UTC with your preferred time zone, although I prefer to see the data as my application do (UTC).

**Comment by ReeganExE** [comment]
For Mac users:
```sh
/Users/hanh/Applications/DBeaver.app/Contents/Eclipse/dbeaver.ini
# OR
/Applications/DBeaver.app/Contents/Eclipse/dbeaver.ini
```

Append the config to the end of file then restart DBeaver.
```diff
 -Duser.timezone=Asia/Ho_Chi_Minh
```
List tz: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
