### ISSUE TITLE
Query results not refreshing in "Production" connections

### ISSUE THREAD

**Issue by zsom** [serge-rider/dbeaver#1226]
Hi!

I'have some connection with "Production" type.
In this connections if i run a query (SELECT * FROM MyTable) multiple times, the results aren't refreshing. The results of the first run is shown allways. I have to disconnect and connect again to get the current results!

There is no problem with "Development" type connections.

If there is a property where I can disable this behavior, or is it a bug?

I'm using DBeaver CE 3.8.5 on Win10. My database is MySQL

Zsom

**Comment by serge-rider** [comment]
This is because Production connections are "transactional" by default.
To see changes made by other applications you have to end current transaction (perform commit or rollback). Or you can switch to auto-commit mode. All these actions available in main toolbar/menu.

This is MySQL specific behavior.

**Comment by zsom** [comment]
Thanks for the answer.
Commiting after the select solves my problem. But it's a bit strange to me, that I have to commit a SELECT statement.

**Comment by serge-rider** [comment]
Yep. That's how MySQL works (by default).
You could also try to change transaction isolation level.
