### ISSUE TITLE
CSV Null interpretation

### ISSUE THREAD

**Issue by CMCDragonkai** [serge-rider/dbeaver#1234]
When exporting CSVs, I suggest that there should be an extra option of selecting how to represent NULLs.

Options:

1. Empty field
2. `NULL`
3. `\N`

If option 1 is available, another option should appear, which is that an empty string should be outputted as `""` and not just an empty field.

The latter 2 options are automatically recognised by MySQL.

**Comment by serge-rider** [comment]
Makes sense

**Comment by CMCDragonkai** [comment]
Choosing the latter 2 options should mean another option as well, that is if a field is in fact string `"NULL"` or string `"\N"`, then there should be a choice to always quote these characters rather than leaving as as literal `NULL` or `\N`, because they are strings and not interpreted NULLs.

**Comment by serge-rider** [comment]
NULL string config will be added on CSV export settings page.

**Comment by CMCDragonkai** [comment]
Cool. So are all options present? Because not everything works like MySQL. I just had a look at the recent commit.

**Comment by serge-rider** [comment]
You can just set any string you want.
That's one option.

**Comment by CMCDragonkai** [comment]
But they can't actually be strings. They have to be literals. For example:

1. Option 1: Literal Nothing: `,,`
2. Option 2: Literal NULL: `,NULL,`
3. Option 3: Literal \N: `,\N,`

Or am I misunderstanding something?

Also I wanted to add that if one of the choices is chosen, then the corresponding string form must be quoted. That is:

1. Option 1: Empty String: `,"",`
2. Option 2: NULL String: `,"NULL",`
3. Option 3: \N String: `,"\N",`

**Comment by serge-rider** [comment]
I don't understand. What's the difference between string and literal in this case?
You can use any sequence of characters to represent nulls. If you need "Nothing" - leave it empty.

**Comment by CMCDragonkai** [comment]
If you have a csv field with `"NULL"`, databases such as MySQL would interpret that as a string and load it as such. However if you instead have the literal `NULL`, with no quoting surrounding it. Then it will interpreted as a *real* NULL field.

**Comment by serge-rider** [comment]
You can specify any sequence of characters, quoted or unquoted, with spaces and any possible form of quotation - anything.

**Comment by hmontone** [comment]
So, if I have a table:

```sql
CREATE TABLE t (
  c1 VARCHAR(255),
  c2 VARCHAR(255) NOT NULL
)
```
, and there is a line where `c1` is `NULL` and `c2` is an empty string, is it possible to export and import that as CSV? I am not talking specifically about MySQL, in fact I currently use IBM DB2. In my tests non-quoted `NULL` is imported as string containing "NULL". One idea would be to interpret empty value without quotes as NULL and empty value with quotes as an empty string. I would like to import relatively big set of data, I am afraid that using `INSERT` -clauses would make file unnecessarily big. In fact, that would choke DBeaver if opened in it.

**Comment by hmontone** [comment]
I believe you are correct. It seems that often some special string (e.g. `\N`) is used to represent `NULL` in CSV. But I am not the first one who has had that idea, that `"",,""` is interpreted as `empty string, NULL, empty string`. It is a workaround and not a clean, proper solution, but in my mind it seems to represent that data correctly from the file format perspective.

My problem has not that much to do with any proper migration, but about trying to do some basic performance testing locally. DBeaver has mock data generation option, but I am afraid that is too simple for the data structure and composition in this case. Our common development environment would have good set of realistic test data, but because of certain reasons it is in this case a bit too clumsy to use.

I guess I could work around this by using for example `\N` to represent NULL, and then `UPDATE` those values back to `NULL` afterwards. Except that not all of them are of character type. And it makes some extra work.

**Comment by hmontone** [comment]
I updated my comment, sorry. 

I think ideally it would need some changes in export too, but I think you are right, I need to create new ticket.
