### ISSUE TITLE
To Upper Case short cut is not working in RHEL-7 with Postgres 9.2.18 

### ISSUE THREAD

**Issue by jrich8573** [serge-rider/dbeaver#1248]
The "To Upper Case" short cut (Shift-Ctrl+U is not working in RHEL-7 with a Postgres 9.2.18 connection, and default key bindings.  I have attempted both the key binding and selecting the action in the edit menu, with sample result. The action returns an underlined lower-case u.

The functionality appears to work correctly in in Windows, with both an Oracle 12g and SQL server 14 connection, again with the default keys bindings.

**Comment by serge-rider** [comment]
Wow, <ins>underlined?</ins>. I didn't know that SQL editor can render that ;)
Looks a bit crazy. This function is provided by Eclipse framework, will try to reproduce that on RHEL..

**Comment by serge-rider** [comment]
I believe this happens because of conflict of Ctrl+Shift+U with native RHEL shortcut. Most likely this one: http://superuser.com/questions/358749/how-to-disable-ctrlshiftu-in-ubuntu-linux

Solutions:
1. Redefine shortcut in DBeaver preferences (any shortcut can be redefined on Keys page)
2. Disable this shortcut in Linux (see above)

**Comment by jrich8573** [comment]
Remapped the key binding, and functionality is working as it. Thanks for the help.
