### ISSUE TITLE
No database selected after startup

### ISSUE THREAD

**Issue by GiantCrocodile** [serge-rider/dbeaver#1251]
1. Start DBeaver
2. Open new SQL editor
3. run a query like "SELECT * FROM < some table>"

Error: No database selected even though at the dropdown at the top there's a database selected (first one in dropdown).

**Comment by serge-rider** [comment]
Well, I don't see any error in current behavior.
Please provide more details. What "no database selected" means and why it is a bug?

**Comment by GiantCrocodile** [comment]
No database selected is the error I get @serge-rider:
"Query execution failed
Reason:
SQL Error [1046] [3D000]: (conn:187) No database selected
Query is: Select * FROM ..."

At the dropdown to select a database there is one selected. If I open dropdown and click on same database again I can run the query. DBeaver seems to forget to call 'USE < database>' on startup.

**Comment by serge-rider** [comment]
Yep, it is a bug in database selector. It should show `<none>` instead of first database in the list.

**Comment by GiantCrocodile** [comment]
Can you make it remember the last choice maybe? I prefer that over setting it manually every startup.

**Comment by serge-rider** [comment]
Just set database name in connection properties.

**Comment by Khazbs** [comment]
What if there is no database and I want to create one? When trying to execute "CREATE DATABASE" using DBeaver, it says "no database selected" and fails to create one.

**Comment by givihuda** [comment]
This happens to me without DBeaver even having to close... when just unlocking my Mac in the morning, after having used several query tabs started from an already-connected database schema. I'm using version 22.3.0.202212041619.

Here's what I did to have it happen:
1. Right-click the database schema (MySQL), select SQL Editor > New SQL Script.
2. Make any SELECT query, run it and see results.
3. Lock the Mac then go to bed.
4. Unlock the Mac in the morning, try running the query again, and get the error.

Here's what didn't fix it:
1. Executing the query using Ctrl+Enter or any other execution method (like one of the buttons).
2. Right-clicking the schema or database and selecting Refresh, then trying to execute again.
3. Right-clicking from within the query tab, selecting Execute, then either 'Set active connection' or 'Select active schema', choosing the same database name or schema name that's already in the tab's name, then trying to execute again.

Here's what did fix it:
1. Closing DBeaver, saving tab unsaved tabs when prompted, opening DBeaver again, then executing the query.

I don't know how to explain this, but the query tabs just become irretrievably disconnected after a while, and I'm not sure what causes this. Maybe the Mac went to sleep, and DBeaver can't handle that? I figured if the query tab's name already contains the names of the database and schema that it would understand those are what the query tab is for, but it forgets for some reason, and sometimes just cannot connect again no matter what I do unless I just restart the app.

Any explanation for this? I think this is far beyond an improper naming situation... the tab names should stay the same, never switch to 'none' or whatever, and should retain/refresh the association/connection of the tab to its database and schema, even if that requires a manual re-connect (though I don't see why it should, it should reconnect when I try to run the query again). I haven't had this sort of issue with MySQL Workbench in the many years I've used it, I just haven't used it recently because of some unrelated crashes. DBeaver can do better.

**Comment by yogevmets** [comment]
Here is how I fix it:
1. Close the script
2. Right-click the database schema (MySQL), select SQL Editor > Open SQL scrip
3. select the desired script

Should work normally

**Comment by givihuda** [comment]
@yogevmets That's a good alternate solution if only 1 tab is having a problem.

I don't know why this issue is closed if the problem is still happening.

**Comment by panostim** [comment]
I had the same problem. I fixed it by editing the connection, there is an Initialisation tab. There, you can select your default database (it means the schema of your choice).
