### ISSUE TITLE
How to change the encoding when view an image type field in sqlserver table with text mode?

### ISSUE THREAD

**Issue by wtslh** [serge-rider/dbeaver#1294]
When view a image type field in sqlserver table with text mode, there's no way to change the encoding,so maybe it only show some unreadable characters.
![dbeaver](https://cloud.githubusercontent.com/assets/2245560/23148002/2731e82e-f81e-11e6-9450-0d40210b731a.png)

**Comment by serge-rider** [comment]
I don't understand the problem. What the point to change encoding if this is a binary data? 
You can view in hex mode. And, if this is an image in supported format (gif, png, jpg, bmp) then you can view it as image.

**Comment by wtslh** [comment]
Dbeaver provides an editor like the picture I post.Binary view shows hex mode,but if swich to Text view,I think there should provider the ability to customize the text encoding just like any text editor run in Windows(editplus,notepad++,etc.)

**Comment by serge-rider** [comment]
This is actually a bug. DBeaver ignores encoding settings. Will be fixed in the next version:
1. Default encoding can be configured in preferences (Result Sets->Binaries). It can be configured for each connection.
2. There is encoding combobox in main toolbar of LOB editor. Changing encoding will change current editor encoding.

**Comment by serge-rider** [comment]
BTW you can test it in EA version (http://dbeaver.jkiss.org/files/ea/)
