### ISSUE TITLE
PostgreSQL Schema

### ISSUE THREAD

**Issue by dizdi** [serge-rider/dbeaver#1303]
There should be an option not to use the schema selector for PostgreSQL. The schema selector overwrites search_path. But if you have multiple schemas like "schema1,schema2,schema3" it's overwritten with "$user",>selected schema< after connect to db.

**Comment by dizdi** [comment]
In 3.8.5 the search_path was not overwritten

**Comment by serge-rider** [comment]
Well, I see what is the problem. Search path mustn't be changed unless user changed active schema explicitly.

This happens because PostgreSQL acts differently than other databases in regards to active schema get/set. So this is a bug in DBeaver connection initialization routine. Will fix it in 4.0.1.
