### ISSUE TITLE
Slow SQL Editor Keyboard and Mouse Event Response

### ISSUE THREAD

**Issue by sephjfox** [serge-rider/dbeaver#147]
Hey guys, just wanted to bring something to your attention. My SQL Editor has become extremely slow, it takes about 1500ms to respond to any keyboard or mouse events. I looked around on google and on the forums a little bit and didn't notice anyone else experiencing this issue.

I'm running dbeaver 3.5.8 out off Debian 8.0 64 bit KDE install using NVidia video drivers, everything else runs super fast. In the past, my SQL editor was also super fast.

I was running 3.5.2 when I first encountered the issue, so I upgraded to 3.5.8 but still experienced the issue.

Does anyone have any idea what could cause this kind of lag in the event loop for the SQL editor text area?

**Comment by codebling** [comment]
What kind of connection is this SQL editor associated with?  If you switch it to a connection of a different type (or even `<None>`) using the Active Datasource drop-down in the toolbar, is the lag still there?

**Comment by sephjfox** [comment]
Alright, I currently have mine setup for connection to a local server and a remote server. Both are MySQL. I alternated between my local, remote, and <none> settings available in the active data connection drop down menu. I swapped between them in various fashions and noticed there was no perceptible change in the lag.

Here is some information about the MySQL driver:

com.mysql.jdbc.Driver
mysql-connector-java-5.1.38.jar

**Comment by codebling** [comment]
Sorry, I thought I had seen in the latest release notes that Serge had added custom SQL completion for MySQL, but this is not actually the case. So switching datasources would not have changed anything, even if you had switched to a non-MySQL connection. 

I'm not able to reproduce this. 

* Which Java are you using? 
    Example: 
```
$ java -version
java version "1.7.0_91"
OpenJDK Runtime Environment (IcedTea 2.6.3) (7u91-2.6.3-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)
```
* What was the last DBeaver version whose SQL Editor worked well for you?
* If you open a brand new SQL Editor window and type a letter, does the lag occur right away? Does it only occur when completing table names, or command names?

**Comment by sephjfox** [comment]
Ah, no worries good sir! We're taking shots in the dark here after all.

* Java version 1.7 OpenJDK

```
java version "1.7.0_75"
OpenJDK Runtime Environment (IcedTea 2.5.4) (7u75-2.5.4-2)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)
```

* I was using 3.5.2 without issue for quite some time, and then one day it started lagging! I haven't added any third party software or done any updates since installing 3.5.2 either. This machine is a pretty persistent environment. I've got the original 3.5.2 folder alongside my 3.5.8 folder.

* If I open the new SQL editor like a ninja and press 'a' it takes the usual ~1500ms to appear. Typing an entire word is quite painful so for the meantime I've been using the mysql command line. I've typed out some stuff for you and the auto complete drop down seems to appear along with the same frequency of updates as the other letters.

Mind you this is the same behavior with selecting text.

This may be helpful:

I copy and pasted in a lot of text, and I can scroll very fast UNTIL the cursor at the bottom becomes visible. Then the 1500ms lag hits start coming. If I scroll up slowly until the cursor loses visibility, the GUI stops lagging and the text scrolling suddenly becomes very fast. As soon as I scroll back down to the cursor it lags on me.

I'm running an Intel i4790K with 16GB of DDR3.

**Comment by codebling** [comment]
Hmm. This is something that Serge will have to take a look at but if there's a bug it will probably wind up be with the Eclipse framework rather than with DBeaver itself. 

With that in mind, I searched for Eclipse bugs related to the lag. Several others have reported seeing massive typing lag, always using an Nvidia card and always on linux systems.

At least one user was able to get around this by changing their Nvidia driver:
https://www.eclipse.org/forums/index.php/t/810894/

Possibly also related: 
https://bugs.eclipse.org/bugs/show_bug.cgi?id=413858#c6


Sorry to continue to ask potentially unhelpful questions and force you to do more work. Would you mind checking on all processes' CPU usages while you're experiencing the lag?  If what you're experiencing is a case of the bug listed above, then your Xorg CPU usage should be quite high while the typing is lagging. If you felt like it/were comfortable with it, you could also try switching your Nvidia driver to the one listed in that first link. 

Of course, if what you're experiencing is related to what's the bug in those links, it would seem to imply that either your video driver was changed or your Xorg config was changed and that is what caused your editing to become laggy. Since you said that your system is pretty stable, it doesn't seem like this is the case. 

Either way, Serge will probably have enough info to make an informed decision about the next move, now !  Thanks for helping to try to figure this out !

**Comment by sephjfox** [comment]
**Success!!**

The root cause is the XFCE4 window hardware compositing manager, I disabled it and the **LAG IS GONE!!!**

Here's my process, as it may be helpful to someone.

I tried all the options you suggested in order, first I absolutely hammered my keyboard into the SQL editor while watching detailed HTOP output. My cpu list lag pointed straight to multiple (several dozen) threads coming out of dbeaver directly like this:

```
/usr/bin/java -jar /home/user/dbeaver.3.5.8//plugins/org.eclipse.equinox.launcher_1.3.100.v20150511-1540.jar -os linux -ws gtk -arch x86_64...
```

I carefully read through the bug report you sent me and tried their options as well as options from related bug reports, rolling back to the earlier Nvidia driver 304, adding AccelMethod Option xaa to xorg.conf Devices, etc, all to no avail.

However, it occurred to me that the problem may not be with the Nvidia driver but with the compositing manager (xfwm4) so I turned it off and voila. **Problem solved.**

* Run xfwm4-tweaks-settings
* Click Compositor Tab
* Uncheck 'enable display compositing'

I appreciate your help, as this would have literally never occurred to me as a potential solution. I'm not sure how much you guys can do to prevent this bug programmatically, but at least causality has been identified.

DBeaver 4 life!!

Thank you for your time sir, it is VERY appreciated.

Cheers,
JJ

**Comment by codebling** [comment]
Wow!  Amazing!!  Great job finding that !  Thanks for figuring it out! 

Someone literally just reported another bug about this, I wonder if it will turn out to be the same thing! 

Thanks again!

**Comment by schaerli** [comment]
+1 Thank you a lot…

**Comment by nospotfer** [comment]
I have the exact same bad behaviour on Dbeaver 5.2.3 - Ubuntu 18.04 .
The problem is, in Gnome I have no idea about how to disable this "enable display compositing" setting.

The process that is causing dbeaver to scroll slowly is this one:
/usr/lib/xorg/Xorg vt2 -displayfd 3 -auth /run/user/1000/gdm/Xauthority -background none -noreset -keeptty -verbose 3

I have a quite decent machine and never had such issues before. I do have a NVidia GPU but it is hard to believe that it could be the source of this issue...

Any hints? thank you!

**Comment by nospotfer** [comment]
Fixed -> It is indeed something related with NVidia.
switched to intel integrated graphics with sudo prime-select intel and rebooted. now everything works smoothly.

**Comment by midnightradio** [comment]
> Fixed -> It is indeed something related with NVidia.
> switched to intel integrated graphics with sudo prime-select intel and rebooted. now everything works smoothly.

I'm in the same situation but need responsive dbeaver editor and nvidia at the same time. Somebody please teach me where can I find "display compositing" setup menu in gnome environment to disable.

**Comment by kovacs-zsolt-sandor** [comment]
25.0.2 Unusable, hated, deleted. Restrore 21.0
