### ISSUE TITLE
JSON - Pretty printer - beautifier

### ISSUE THREAD

**Issue by firehooper** [serge-rider/dbeaver#1531]
Option to format the minified jsonb fields when in viewer

**Comment by lacanoid** [comment]
This should also work for plain json datatype and possibly all text formats.
Sometimes on has a domain like geojson defined over json/jsonb.
Beautifier should probably be useful for these cases as well.

**Comment by qyloxe** [comment]
And please add value formatter available for any field type - ther could be XML or JSON in any text type, and I would like to format and view it accordingly:

![image](https://cloud.githubusercontent.com/assets/467508/24749045/ebfd2342-1ac1-11e7-85e6-614cc38b3cab.png)

**Comment by loskultos** [comment]
i second this -  for me and my colleagues it's one of the most awaited features

**Comment by serge-rider** [comment]
JSON viewer is included in EE version (it was initially developed for MongoDB documents viewer).
Probably it will be moved to CE version soon. 
Could you test it?

**Comment by qyloxe** [comment]
Sure, tell me what to do. 
I can execute different sql queries with JSON results as text, json and jsonb and partial json, and see if it works.

**Comment by serge-rider** [comment]
Just download EE version and execute the same queries.

**Comment by qyloxe** [comment]
Testing EE version. Here is the script sequence:

--test JSON & JSONB data type conversion for scalar values
SELECT 
  'null'::json, 
  'true'::json, 
  'false'::json, 
  '2'::json,
  '1.0001'::json,
  '"abc"'::json, 
  '1E7'::json, 
  '1E7'::jsonb;

![image](https://cloud.githubusercontent.com/assets/467508/24956131/87072eb4-1f86-11e7-9b8b-b8b0f4fc08cd.png)

TEST RESULT: data type recognised properly, formatter for scalar values is OK

-- prepare data
CREATE TABLE IF NOT EXISTS json_test (
  id serial primary key,
  data jsonb
);
TRUNCATE table json_test;
INSERT INTO json_test (data) VALUES 
  ('{}'),
  ('{"a": 1}'),
  ('{"a": 2, "b": ["c", "d"]}'),
  ('{"a": 1, "b": {"c": "d", "e": true}}'),
  ('{"b": 2}');

-- test full recordset
SELECT * FROM json_test;

![image](https://cloud.githubusercontent.com/assets/467508/24956233/0abe4db4-1f87-11e7-974b-000eb19822b7.png)

TEST RESULT: data type recognised properly, formatter for json values is eseentially the same as for text data type only with colors applied, which is bad. Red arrow points to proposed new option "format/pretty print" in content viewer menu.

-- test pretty formatting from postgres
SELECT jsonb_pretty(data) FROM json_test;

![image](https://cloud.githubusercontent.com/assets/467508/24956359/89022d9e-1f87-11e7-8c9c-4b8a0e1db1e4.png)

TEST RESULT: data type recognised as text which is formally proper. formatter for resultset is somewhat weird with special characters (I assume it is possible to disable special chars presentation in resultset). There is no content viewer menu - which is extremely BAD! I want to apply content viewer to any cell/column result which could be presented as text and could hold JSON/XML or anything (CSV even).

-- cleanup
drop table json_test;

-- test JSON constructed from "normal" tables - VERY IMPORTANT! 
with subquery
as (
  select 
  pa.datid,pa.pid,pa.usesysid,pa.application_name,pa.backend_start,pa.query_start,pa.state_change,pa.state
  from pg_stat_activity pa
  order by pa.state,pa.query_start
  limit 1000
)
select json_agg(json_build_object(
'datid',datid,'pid',pid,'usesysid',usesysid,'application_name',application_name,'backend_start',backend_start,'query_start',query_start,'state_change',state_change,'state',state
))  as result
from subquery;

![image](https://cloud.githubusercontent.com/assets/467508/24956491/21e1a21a-1f88-11e7-90e5-e0ec8e41f720.png)

TEST RESULT: real world example - fragment of JSON API which is presented as web service. The result is unreadable. Expect even 100s of kB of JSON results in production.

-- test text representation of JSON constructed from "normal" tables - VERY VERY VERY IMPORTANT! 
with subquery
as (
  select 
  pa.datid,pa.pid,pa.usesysid,pa.application_name,pa.backend_start,pa.query_start,pa.state_change,pa.state
  from pg_stat_activity pa
  order by pa.state,pa.query_start
  limit 1000
)
select cast(json_agg(json_build_object(
'datid',datid,'pid',pid,'usesysid',usesysid,'application_name',application_name,'backend_start',backend_start,'query_start',query_start,'state_change',state_change,'state',state
)) as text)  as result
from subquery;

![image](https://cloud.githubusercontent.com/assets/467508/24956598/9a0aba4c-1f88-11e7-9fde-0b9f9f3d495a.png)

TEST RESULT: real world example - fragment of JSON API which is presented as web service. There is no result, because data is converted to text, so the conten viewer submenu is disabled - BAD

**Comment by serge-rider** [comment]
I will add JSON formatting in the next version.
The only question is - should this be configurable. 
Should we leave original formatting in some cases?

**Comment by lacanoid** [comment]
You could run the beautifier always when loading the value inti json editor, but initially flag the field as unchanged so that it doesn't save unless the user actually types/cuts/pastes something there.

Not that the Postgres json type (as opposed to jsonb) is just text, validated by json syntax. It preserves white space, comments, key order, repeated keys, etc. It might make sense to use a beautifier which works on a text/syntax level (as opposed to one that actually loads and then dumps the json structure). This would preserve the comments, the order etc... and work as expected. Might also use a bit less memory (see above comment about memory use)

**Comment by lacanoid** [comment]
Perhaps the best thing would be to provide a checkable menu option, just like for word wrapping then run the beautifier upon editing or loading the value if the option is checked. This way it tries to work usefully by default, but it can still be turned off if desired.

**Comment by lacanoid** [comment]
More difficult problem seems to be how to choose the appropriate content viewer type and when to change it automatically. In any case, the content editor menu should likely always be present (see @qyloxe's comment)

**Comment by qyloxe** [comment]
@lacanoid - comments of the form //… or /*…*/ are not allowed in JSON. Based on:

http://www.json.org
RFC 4627: The application/json Media Type for JavaScript Object Notation (JSON)
RFC 7159 The JavaScript Object Notation (JSON) Data Interchange Format - Obsoletes: 4627, 7158

**Comment by lacanoid** [comment]
I see. My bad :(

Multiple same keys and key ordering are still relevant, though. It is one of the reasons a separate jsonb type was created for postgres as some people were/are happily (mis)using json for those very features. Maybe not the best practice, but quite possible.

**Comment by serge-rider** [comment]
See fixes in 4.0.5 EE.

**Comment by lacanoid** [comment]
Awesome! This is the greatest DBeaver release yet!

**Comment by firehooper** [comment]
Thanks for adding this!

**Comment by darrinholst** [comment]
👍 great job!

**Comment by verglor** [comment]
Hi @serge-rider, are you still considering moving this to CE version ?

> JSON viewer is included in EE version (it was initially developed for MongoDB documents viewer).
Probably it will be moved to CE version soon.
