### ISSUE TITLE
Limit maximum memory consumption

### ISSUE THREAD

**Issue by serge-rider** [serge-rider/dbeaver#1541]
On machines with big amount of memory (16gb+) DBeaver may consume big part of it. By default Java may eat to much. But in fact DBeaver doesn't need so much memory, it is mostly spent on lazy GC.
I think that by default DBeaver shouldn't consume more than 1gb.

However this may lead to some side-effects.

**Comment by anophelesgreyhoe** [comment]
I re-opened DBeaver a few hours ago and right now it's consuming 8.9 GB of virtual memory. Between DBeaver, Chrome, Firefox, and occasionally JDeveloper, I have to be a little careful as I've had occasions of thrashing where my computer has been unresponsive for as much as 1 hour.

On some occasions I've had to ssh into my PC and kill processes because the UI was dead.

From some reading I did the last time this happened I got the impression that Linux is somewhat poor at maintaining responsiveness when dealing with out of memory type situations.

**Comment by carlosspohr** [comment]
Uhmmm, what about use eclipse.INI args to do it?

On Apr 6, 2017 10:20 PM, "anophelesgreyhoe" <notifications@github.com>
wrote:

I re-opened DBeaver a few hours ago and right now it's consuming 8.9 GB of
virtual memory. Between DBeaver, Chrome, Firefox, and occasionally
JDeveloper, I have to be a little careful as I've had occasions of
thrashing where my computer has been unresponsive for as much as 1 hour.

On some occasions I've had to ssh into my PC and kill processes because the
UI was dead.

From some reading I did the last time this happened I got the impression
that Linux is somewhat poor at maintaining responsiveness when dealing with
out of memory type situations.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/serge-rider/dbeaver/issues/1541#issuecomment-292388645>,
or mute the thread

**Comment by serge-rider** [comment]
Default maximum memory set to 1024mb. Default initial memory to 64mb.

@anophelesgreyhoe this sounds like a typical GTK problem. Try to run `export SWT_GTK3=0` before running DBeaver.

**Comment by r-richmond** [comment]
Is there an option where i can change both maximum memory and default initial memory?

context: I've noticed dbeaver is running a little slower on my machine and the memory its using never goes above 71mb (according to heap).

I have plenty of memory and i'd like to see if changing these settings improves my experience.

**Comment by serge-rider** [comment]
You can change memory settings by modifying dbeaver.ini - `-Xmx` and `-Xms` parameters (refer readme.txt for details).
However default maximum memory size if 1Gb for CE and 2Gb for EE. This should be enough. Can't say why it is always 71mb in your case.

**Comment by r-richmond** [comment]
on a mac not seeing a `.ini` or readme.... glanced through the wiki and didn't see anything... feel like i'm missing something obvious

**Comment by serge-rider** [comment]
On Mac it is in Contents/Eclipse subfolder.

**Comment by r-richmond** [comment]
found it thanks.
