### ISSUE TITLE
Forbidden to download JDBC files

### ISSUE THREAD

**Issue by esambo** [serge-rider/dbeaver#1561]
http://dbeaver.jkiss.org/files/jdbc/ returns a `403 Forbidden` status code from Apache which prevents me from updating my PostgreSQL driver!

**Comment by serge-rider** [comment]
JDBC drivers are taken from Maven repository (at least for PostgreSQL). http://dbeaver.jkiss.org/files/jdbc/  doesn't contain any new driver versions (starting from DBeaver 3.0).

If you don't have access to Maven central repository (due to restricting firewalls or something like this) then you need to go PostgreSQL web site and download recent drivers from there.
