### ISSUE TITLE
Statistics tab - Show "Updated Rows" in the first line

### ISSUE THREAD

**Issue by gusehr** [serge-rider/dbeaver#1567]
Hi there!

Thanks for DBeaver!
It is an amazing database tool.

I have an UI suggestion for the statistics tab (shown after an "update" statement, e.g.).
The first line can be the "Updated rows" information, and then the "Query" and "Finish time".
I think that the rows information is the most relevant for this tab.

Thanks in advance.

**Comment by serge-rider** [comment]
Ok. This is not relevant for me but if it is important for someone - no problem.

**Comment by KoenVerbeeck** [comment]
Small question. I'm running version 6.1.5 and connecting to the Snowflake database. I'm running a COPY INTO statement and instead of getting results back in the result tab (a line for each file I'm trying to import), I get this statistics tab, which is quite useless for the COPY INTO statement. I can't find a setting that changes this.
