### ISSUE TITLE
Script begins with comments = error

### ISSUE THREAD

**Issue by charlie17** [serge-rider/dbeaver#1670]
I have several scripts, each of which begins with comments. If I `Alt-X` this it throws an error as follows. If I remove the comments at the top the script will run. Any way to address this?

![image](https://cloud.githubusercontent.com/assets/4766631/26157157/77514736-3ae6-11e7-9300-e15476926254.png)

**Comment by serge-rider** [comment]
What is your database?
Could you post a sample of such script?

**Comment by charlie17** [comment]
It is postgres.

Even the following simple test will trigger the error. If I only execute the select line, it works. But if I execute all (via `Alt-X` or via `Ctrl-Enter`), it triggers the error.

`﻿-- comment`
`select * from test;`

**Comment by serge-rider** [comment]
Well, you sample contains invisible BOM mark (0xFEFF) before first comment dash. DBeaver parses it correctly and passes to PostgreSQL - but query fails because PG doesn't understand (obviously) BOM before query.
Looks like you copy-pasted your query from some external source. 
Solution: just delete first dash and type it again.

**Comment by charlie17** [comment]
Very odd. I will look into this. Thanks for the quick replies
