### ISSUE TITLE
[Feature Request] Switch between most recent tabs

### ISSUE THREAD

**Issue by Karsonito** [serge-rider/dbeaver#1679]
I like to switch between recent tabs in browser with Ctrl+Tab shortcut.
II'd appreciate somebody add this possibility in dneaver!
Ctrl+PageUp/Down is not the same
Ctrl+Tab can save a lot of time!
Thanks for great tool!

**Comment by kyleflan** [comment]
This won't let you switch between the most recent tabs, but you can enable Ctrl+Tab to switch between tabs similarly to Chrome and other applications. 

Open Preferences -> General -> Keys. Search for "Next Tab". Click in the "Binding" text field and hold down Ctrl and Tab to grab the keybinding. Leave "When:" set to "In Windows". Repeat the process searching for "Previous Tab" and use Ctrl+Shift+Tab as the key combo. 

![image](https://cloud.githubusercontent.com/assets/5608074/26326327/47aecf4e-3f00-11e7-95dd-028afa55db26.png)

One caveat is that this will not "wrap" around the tabs, i.e. you cannot switch from the last tab back to the first by typing Ctrl+Tab.

**Comment by Karsonito** [comment]
@kyleflan Thank you for advice, but this is not the same. Especially when I opened many tabs.

**Comment by kyleflan** [comment]
What about doing the same steps above, but search for "Next Editor" and "Previous Editor" and bind those commands to "Ctrl+Tab" and "Ctrl+Shift+Tab"? Then Ctrl+Tab will take you to the most-recent tab (and you can cycle backwards using Ctrl+Shift+Tab).

**Comment by Karsonito** [comment]
Oh yeah! This is exactly I was looking for! Many thanks!
Issue is solved and could be closed

**Comment by Karsonito** [comment]
@serge-rider 
May be default shortcuts should be changed to "Ctrl+Tab" and "Ctrl+Shift+Tab" ?
Because Ctrl+F6 and Ctrl+Shift+F6 are not obvious. And it is hard to find and understand meaning of "Next Editor" shortcut.

**Comment by kyleflan** [comment]
DBeaver is based on the popular Eclipse IDE and inherits most of its default behavior and keybindings. While Ctrl+Tab seems more intuitive to you (and me too, since I don't have a long history in Eclipse), it would be very counterintuitive to the majority of users who use DBeaver. Ctrl+F6 is the Eclipse standard for moving through recent tabs.

**Comment by ryancabanas** [comment]
This capability of using keyboard shortcuts to navigate between tabs was exactly what I was looking for.  Thanks!  I did discover a bug in v4.2.2 with regards to this, though.  Can you tell me where I would report this?  The bug is related to what you mentioned about not being able to use Ctrl + Tab to wrap around from the last tab back to the first tab.  The but is that if you are at the last tab and you accidentally press Ctrl + Tab and then you try to press Shift + Ctrl + Tab to start moving backwards in the tab sequence, Shift + Ctrl + Tab doesn't work.  This seems to only happen when you accidentally pressed Ctrl + Tab when at the last tab beforehand.  Thanks!

**Comment by serge-rider** [comment]
@ryancabanas You can report bug right here. Click on green button `New Issue` in the top right corner of this page.

**Comment by ryancabanas** [comment]
@serge-rider Thanks!

**Comment by Taariqq** [comment]
> What about doing the same steps above, but search for "Next Editor" and "Previous Editor" and bind those commands to "Ctrl+Tab" and "Ctrl+Shift+Tab"? Then Ctrl+Tab will take you to the most-recent tab (and you can cycle backwards using Ctrl+Shift+Tab).

Why is it that when I map these two to Ctrl+Tab and Ctrl+Shift+Tab, sometimes the editor switches right away and sometimes it gives me a list of tabs, with the intended tab selected? It is just one more keystroke but it is very annoying, especially when it is not consistent!

**Comment by givihuda** [comment]
Note that Preferences -> General -> Keys is now Preferences -> User Interface -> Keys.
