### ISSUE TITLE
Advanced Paste problem

### ISSUE THREAD

**Issue by TrampolineMan** [serge-rider/dbeaver#1705]
I would like to paste several rows without erasing existing data. When doing advanced paste for several rows existing data will be ovewritten.

I have tried to insert a new row but the new row is alwawys inserted above the last previously existing line. This means the last line will be overwritten. If I try to sort after inserting a row the new row will dissapear. I have also tried to insert a new row and adding some fake data, then sorting so it ends up last and then paste advanced. The last method sort of works but it is unnessecarily cumbersome and it is problematic. E.g. the fake values need to be such that it sorts last and does not violate key constraints.

The problem could be resolved in at least 3 ways:
1. Insert inserts a new row after the last one rather than above currently
2. Allow an advanced paste command that paste to end of table regardless of what part of the table is selected
3. Do as in PgAdminIII and MS Access: Always secure a blank row at the end of the table for pasting/inserting new data.

**Comment by serge-rider** [comment]
Agreed, pasting a bunch of new rows isn't very convenient.
1 is configurable in preferences (insert after or before current row). I think I'll made "insert after" default.
2 won't work because table may have a lot of rows.
3 will require major code change + I don't like this UI.

Maybe this can be solved like this: if you perform advanced paste over a new row (after alt+insert) then all rows will be inserted as new rows. Otherwise overwrite will be done.

**Comment by serge-rider** [comment]
You can check fixed paste in EA (http://dbeaver.jkiss.org/files/ea/)

**Comment by TrampolineMan** [comment]
Wow! Thank you! 
It works perfectly now!!!

By the way I love the dbeaver: the UI, the responsivness, the functionality, java base. And on top of that the advanced copy/paste sets it aside from competition in a really big way. 
I could never settle for one of the "browser"/wen-components ones. All productivity applications should follow dbeavers suite in design philosophy!
