### ISSUE TITLE
Oracle XMLType displays '[NULL]'

### ISSUE THREAD

**Issue by beirtipol** [serge-rider/dbeaver#171]
Been chasing my tail all morning because I thought our DB was messed up.

Running this from DBEAVER

    select XMLType('<IAmXML>Really I Am</IAmXML>') from dual;

shows

    [NULL]

but in SQLDeveloper it returns the xml

**Comment by serge-rider** [comment]
In order to be able to process XML in Oracle you need two additional jars: xdb6.jar and xmlparserv2.jar (can be downloaded from the standard JDBC download page).
If adding these jars won't help please check error log and debug log (in user home .dbeaver/.metadata folder).
In my environment results fo your query looks like this:
![xml-select](https://cloud.githubusercontent.com/assets/6398845/12550109/9a3988d6-c372-11e5-9f99-95148000e183.png)
Note: there is a bug (already fixed, fix will be added in the next version) in LOB processing which leads to "Cannot delete file" error. To avoid it add some alias to your XML column.

**Comment by beirtipol** [comment]
I suggest you make this requirement explicit to users, because it's not clear that there are missing jars, and it appears that the data in the database is different to what it actually is

**Comment by serge-rider** [comment]
Agreed, I'll add extra jars info for Oracle driver.

**Comment by beirtipol** [comment]
Great, thanjs

**Comment by codebling** [comment]
Hope you didn't waste too much time on it, @beirtipol !!

**Comment by beirtipol** [comment]
Well..... We had a Prod issue reported where the data in our database was reportedly null and I spent a few hours trying to figure out why it was null. Turns out it wasn't:)

**Comment by prstahle** [comment]
How do you add the extra jars? I have tried adding folder, jar file to 'edit driver' dialog. I have tried adding the directory to the classpath of eclipse. I have also added the jar files to the oracle client directory. None of these attempts got me past the ClassNotFoundException for XMLType.

**Comment by serge-rider** [comment]
Just add jar files in driver libraries:
![oracle-driver-files](https://cloud.githubusercontent.com/assets/6398845/16738668/6606e372-479f-11e6-9378-0955e21329e5.png)

**Comment by prstahle** [comment]
For some reason I had to restart eclipse after adding xdb6.jar. After the restart I then got a different error, but I only had to add the rest and then everything worked.

Thanks for your help and screenshot. They helped a lot....

**Comment by dariopnc** [comment]
coming from #1008 

as of DBeaver version 3.8.0 there's no explicit indication of what's the problem, dowload link, etc.

this error window is the only output:
![immagine](https://cloud.githubusercontent.com/assets/15945411/20703448/f07b23a2-b61b-11e6-8457-1428f7b69436.png)

**Comment by sgabisaad** [comment]
Hi there,

I have added the Jar files as attached but and restarted DBeaver but still an issue. Attached log files.

[dbeaver-debug.txt](https://github.com/serge-rider/dbeaver/files/827504/dbeaver-debug.txt)
![capture](https://cloud.githubusercontent.com/assets/26272375/23703497/e0f67964-0408-11e7-9108-29572458d449.PNG)

**Comment by serge-rider** [comment]
Try to restart DBeaver after adding extra jars.

**Comment by sgabisaad** [comment]
I even restarted my machine still the same

**Comment by serge-rider** [comment]
Odd. Maybe the problem is in driver version and/or XDK version. BTW what server/driver versions do you use?

Error is `java.lang.NoClassDefFoundError: oracle/xml/binxml/BinXMLException` but class BinXMLException is definitely in `xmlparserv2.jar`. How did you get this jar?

Note: it is not so easy to download XDK from oracle.com. In many cases it is easier to download SQL developer and get jars from there. Oracle doesn't like easy ways.

**Comment by serge-rider** [comment]
Note2: xmlparserv2.jar is not needed (shouldn't be) for Oracle 11/12.

**Comment by sgabisaad** [comment]
I removed it and tried again after restarting. Attached error log.

I downloaded it from this website:
http://www.java2s.com/Code/Jar/x/Downloadxmlparserv2jar.htm

I am downloading JDeveloper now and will get the file from XDK folder once I install it.
[dbeaver-debug.txt](https://github.com/serge-rider/dbeaver/files/827653/dbeaver-debug.txt)

**Comment by serge-rider** [comment]
Yes, that was incorrect xmlparserv2.jar. I wouldn't recommend to download any such jars (you can't be sure what's inside).

Yes, try SQL developer jars. Or you can try this: http://www.oracle.com/technetwork/database/index-100632.html

**Comment by sgabisaad** [comment]
Not it works after getting the right xmlparsev2.jar from the jDeveloper installation.

**Comment by sixdimensionalarray** [comment]
I just wanted to add, I still needed to add xmlparsev2.jar for the XML features to work, even using the latest Oracle 12.2.0.1 JDBC drivers.  I was able to grab a copy of it from my SQL Developer installation.

This was the list I needed:
![image](https://user-images.githubusercontent.com/3506127/32244297-592b6b10-be35-11e7-9964-001fb3a30bb8.png)

**Comment by phil-flex** [comment]
Added the above jar, the field able to display '[XML]' in field, but it is not able to display the value.
