### ISSUE TITLE
Editing fields and pressing save will not save the last change.

### ISSUE THREAD

**Issue by IHateGlamour** [serge-rider/dbeaver#1726]
Not sure how important this is, but I lost a lot of time and anger not understanding why sometimes the values are wrong, I was thinking it was a bug in my application.

Let's take as example modifying these 2 rows changing id to 6 and pressing Save (can u see any difference?), 
![image](https://cloud.githubusercontent.com/assets/16667414/26630743/c150c728-4610-11e7-906d-ec4b573c85f3.png)
vs 
![image](https://cloud.githubusercontent.com/assets/16667414/26630950/93524b3e-4611-11e7-9adb-477ffae78c6f.png)

In the first case I press Save while the cursor is in the second row, **both rows will shows id 6, but only the first row will get updated** (the second row will have the old value, even if it shows the new one).
In the second case, after modifying the second id I press enter( or press outside the row) and then press Save - both values are updated as expected. 

Tried both DBeaver 4.0.4 and 4.0.8. A strange thing is that I tried same thing on another PC with DBeaver version 4.0.4, and in first case when pressing save it reverts the second row to it's old value (so I see that the second row wasn't updated).

**Comment by kyleflan** [comment]
Short answer: press enter in the cell before clicking "Save".

Long answer:

DBeaver saves changes you've made in the grid locally, and when you click "Save", pushes the changes to the database. In your first instance though, you haven't communicated to DBeaver that you want to make that change for row 2 yet, since you're still editing the cell. Clicking "Save" takes focus away from the cell so it may appear that you've made a change, but you actually haven't. Make all changes you need, press enter after each change, and ensure all cells are highlighted in orange that you want to make changes to. Then click "Save" and your changes will be sent to the database.

I can see where your confusion comes from as I've run into this before.

**Comment by altaraven** [comment]
@kyleflan 
Sorry for a little offtop but, is there an option for field to be saved without pressing "Save" button, just on field change?
