### ISSUE TITLE
Export resultset - run again the query

### ISSUE THREAD

**Issue by collicalex** [serge-rider/dbeaver#1762]
Hi,

When exporting a resultset (right click on result, in context menu, choose export resultset), it's run again the query on the db server which is useless as all the result is already displayed / grabbed.

Moreover, when doing this, it seems that the query is run again inside a transaction; which can cause some troubles. In sybase ASE for example, some sql statement can't be done inside a transaction (select into #tempable from...); which make the result to be no exportable.

**Comment by kyleflan** [comment]
The purpose of Export Resultset... is to export the entire set of records that would be generated by the query that was run. Typically, DBeaver limits this to 200 records in the client at a time to be efficient. So, in order to actually grab the entire result set, DBeaver must requery the database when exporting.

If the result set contains all the records you want to export (be wary of the default 200 record limit), you could do an Advanced Copy to copy and paste the records, though this is much more limited than the export.

An alternative is to highlight the selected query, prior to executing in DBeaver, and right click, Execute -> Export from Query. This saves the step of performing the initial query to populate the Resultset pane. This might or might not help with the transaction issue. I'm not well-versed (aka not versed at all) in Sybase, but it might be worth a shot. 

![image](https://user-images.githubusercontent.com/5608074/27082718-7648c97e-500b-11e7-92a1-cea2d75bc302.png)

**Comment by collicalex** [comment]
The advance copy is working fine. Thanks :)
Just to do not forget to select the whole result (ctrl+a).

But I have then to create the file myself and paste in it.
And if I have 10 resultset to export... I have to do it 10 times, which is a little bit borring.


And what about to copy (i.e. export) to another format than pure text (like excel, I saw that it's in the pipe for "export resultet" feature)? We maybe have an option to "export result" from displayed data or to run again the query to grab all data?

**Comment by collicalex** [comment]
Ok, so if I uncheck the "open new connection" when exporting resultset, I do not have anymore the transaction problem; but I'm getting an error:

![data_export_error](https://user-images.githubusercontent.com/24322371/27126164-df57b380-50f6-11e7-9b2b-df66140103a6.png)

My big query create 20 resultsets.
Is there a limitation when exporting?

**Comment by serge-rider** [comment]
Please post full error stacktrace. You can get it in Error Log view ( or in error/debug logs: https://github.com/serge-rider/dbeaver/wiki/Log-files).

**Comment by collicalex** [comment]
Here are the logs

[log.zip](https://github.com/serge-rider/dbeaver/files/1087520/log.zip)

**Comment by collicalex** [comment]
Just notice that the exported file is created (without all the data) and DBEaver keep the file locked after this crash. Maybe add a "finally" part into the java code to close opened files?

**Comment by serge-rider** [comment]
I've fixed this particular error but I still can't reproduce it. It would be helpful to understand why it happens (looks like real results column count doesn't match expected count).
Could you send a sample of query you are exporting from?
