### ISSUE TITLE
Cannot connect to DB using DBeaver

### ISSUE THREAD

**Issue by rtlenaha** [serge-rider/dbeaver#1898]
When attempting to connect to a PostGreSQL DB using DBeaver, I get the following message when trying to complete the connection (using credentials that have worked with pgAdmin III and 4):
   Can't create driver instance
      Can't load driver class 'org.postgresql.Driver'
           java.lang.ClassNotFoundException: org.postgresql.Driver

**Comment by kyleflan** [comment]
Your credentials are not the issue. DBeaver can't find the JDBC driver for Postgres. In the navigation menu, go to Database -> Driver Manager, click on Postgres and click Edit. Does it show any files under the "Libraries" section? If not, click "Download/Update" to get the latest Postgres drivers.

**Comment by serge-rider** [comment]
It is possible that you don't have direct internet access on your working plan (e.g. because of some corporate proxy).
In this case you could try:
1. Download drivers manually from https://jdbc.postgresql.org/download.html and then add jars in driver editor
2. Try to configure HTTP proxy in preferences

**Comment by Cheilanthe** [comment]
I had the same problem, thanks for the help 🚀

**Comment by laurianops** [comment]
This case happened to me because I updated dbeaver and didn't restart it.
