### ISSUE TITLE
MS SQL Server GO batch support

### ISSUE THREAD

**Issue by juszczakn** [serge-rider/dbeaver#192]
dbeaver doesn't currently seem to support the MS SQL GO keyword. I'm going to look into adding support for it. 

I think I've located the area where query delimiters are gathered, plugins/org.jkiss.dbeaver.model/src/org/jkiss/dbeaver/model/sql/SQLSyntaxManager.java:115

Having a hard time getting the build working on Linux, I'll see how much progress I can make on it.

**Comment by serge-rider** [comment]
Did you try to set "GO" as statements delimiter in Preferences->SQL Editor->SQL Processing?

**Comment by juszczakn** [comment]
@serge-rider I did, unfortunately it only supports a single character it seems.

**Comment by serge-rider** [comment]
I think that this issue can be solved by fixing statement delimiter UI. Single character limitation is actually a bug (this restriction was there a long time ago - now it is gone)..
UI fix will be fixed in the next version.
BTW default SQL Server and Sybase drivers have default delimiter "GO". I assume you are using some manually created driver.

**Comment by serge-rider** [comment]
Workaround: 
- Open connection editor, click on "Edit Driver". 
- Switch tab on "Adv. parameters".
- Set "Script delimiter" value to "go".

**Comment by juszczakn** [comment]
I believe I'm using the default jtds driver. Thanks for the workaround.
