### ISSUE TITLE
Nullpointer exception postgresql diagram

### ISSUE THREAD

**Issue by Yanpas** [serge-rider/dbeaver#2101]
Here is log from "Error log" view in Eclipse.
[diagrampg.txt](https://github.com/serge-rider/dbeaver/files/1260977/diagrampg.txt)
I've opened diagram of one postgresql table and this error occured. Unfortunately I can't provide Schema of database

**Comment by serge-rider** [comment]
This exception happens because DBeaver can't recognize some data types (there are many warnings about that). I have fixed this particular exception but original problem is still there.
Could you say - is there anything special about your schema?
Does full database refresh help (F5 on database node in navigator view)?

**Comment by Yanpas** [comment]
Created same database on another machine (same sql script) with same user and database - I wasn't able to reproduce the issue. I need to take a look at previous machine (I will be able to to it in 1 day).

**Comment by Yanpas** [comment]
Still cannot reproduce, it's like issue has dissappeared :expressionless:

**Comment by serge-rider** [comment]
Potentially it could happen if you created a new schema and DBeaver didn't update data types for some reason.
Anyhow, thanks for report.
