### ISSUE TITLE
Why did some type of database not have the function "create new database"?

### ISSUE THREAD

**Issue by rhjyy** [serge-rider/dbeaver#2126]
Such as MS SQL Server、PostgreSQL……

**Comment by serge-rider** [comment]
Create database is a custom database-specific function. It is implemented only for certain databases.
For PostgreSQL we already have such FR: #2109

**Comment by rhjyy** [comment]
Thanks for your explanation.And if there is an implemented list?

**Comment by serge-rider** [comment]
Not yet, we keep working on documentation.

It is possible to create/drop schema in MySQL, Oracle, PostgreSQL, DB2.
For SQL Server this will be implemented in #810
In PostgreSQL database is different. It is a physical thing and requires a separate connection. That's why it wasn't implemented initially.

**Comment by rhjyy** [comment]
Got it.Thank you very much.
