### ISSUE TITLE
Redshift transition to ACM Certificates

### ISSUE THREAD

**Issue by kevhav** [serge-rider/dbeaver#2183]
I use DBeaver to access Amazon Redshift.

We just got this notification from Amazon, about our Redshift cluster:
https://docs.aws.amazon.com/redshift/latest/mgmt/connecting-transitioning-to-acm-certs.html

It mentions, "Amazon Redshift drivers beginning with ODBC version 1.3.7.1000 and JDBC version 1.2.8.1005 automatically manage the transition from an Amazon Redshift self-signed certificate to an ACM certificate."

I keep DBeaver up to date, and my Redshift driver currently has "1.2.7.1003" in it -- presumably this is the JDBC driver version, right?

Will I need to do anything with DBeaver, in order to continue using it to access my Redshift cluster, after Amazon makes this change to ACM Certificates?

Would you start shipping DBeaver with a newer Redshift driver that handles it? Or would I need to update the driver, manually, myself? (I'm not sure how to do this, but I could probably figure it out.)

Or anything else? Thanks!

**Comment by serge-rider** [comment]
- You can always update driver version (to older or newer) in DBeaver driver manager.
- We can upgrade default RedShift driver version in DBeaver configuration if older version become obsolete. The only concern is about backward compatibility. Maybe it'll make sense to have two different prconfigured drivers. 

What do you think?

**Comment by kevhav** [comment]
For my purposes, I'm happy to just update the driver. 

I'm not 100% sure how to do this, however. I've looked at DBeaver's driver manager. Selecting the Redshift driver file and clicking "Download/Update" doesn't seem to update to a newer version of the driver -- right?

So, I download the corresponding .jar file, from Amazon (it looks like DBeaver wants a JDBC 4.1–compatible flavor of the driver). Then, I open the driver manager in DBeaver. Now, what? Do I select "Redshift" and click "Edit"...then change the Redshift driver? What do I edit?

Or, do I click "New"...and create a new item in DBeaver's driver manager, with the new version of the driver?

I couldn't find the steps documented anywhere. Thanks for your help!

**Comment by serge-rider** [comment]
Download new driver jar.
In driver manager, find RedShift driver. Click on `Edit`.
On tab `Libraries`:
- Select preconfigured library jar (1.2.7.1003) and click on `Delete`.
- Click on `Add file`
- Choose jar file you just downloaded
- Click Ok

That's it.

**Comment by serge-rider** [comment]
I'll create Wiki article for driver management. Thanks for reminder :)

**Comment by kevhav** [comment]
Easy, indeed. That worked, thanks!

**Comment by BigDataDaddy** [comment]
There are a couple of related issues with this particular AWS Redshift driver update.  

1.  As Redshift is a managed service, there really isn't much of a backward compatible concern as AWS will be changing the SSL cert. on all clusters on the dates they announced.  In other words, supporting older Redshift drivers shouldn't be much of concern for DBeaver as AWS will be breaking compatibility anyway.
2.  Redshift is changing the SSL cert. used for all Redshift clusters because the current cert. will expire soon.  So all SQL clients and applications that use encrypt connections with SSL using JDBC, ODBC on the client will have to upgrade their client end driver because AWS is packaging the SSL cert into the driver. Yea!
3. Redshift as part of the changing the SSL cert. they are changing from a self-signed cert. to an Amazon Certificate Manager (ACM) Certificate Authority (CA) signed cert. However, the ACM CA trust chain is not in the default JVM truststore.  This means that in addition to installing the new JDBC/ODBC driver with the new cert packaged in it, the CA trust chain has to be installed into the truststore that's used by the driver, in the truststore of the JVM used by DBeaver for JDBC on all OSes, in the Windows system truststore for ODBC on Windows, and I'm not sure where for ODBC on *nix.  As DBeaver has 3 install modes, packaged installer with JVM, ZIP using separate JVM, and Eclipse plugin using Eclipse JVM. there are 3 possible scenarios for installing the ACM CA trust chain into the truststore used by the JVM DBeaver uses.  I respectfully request that DBeaver always add this new ACM CA trustchain to the JVM in the packaged install.  I've been doing manual JVM trust chain installs for some other tools that package a JVM and overwrite the JVM every new minor version upgrade and I can tell you it a huge pain a barrier to keep using the tool when an installed trust chain keeps getting overwritten.

Everything that's needed to do this is available for public download directly from the Redshift doc.

**Comment by serge-rider** [comment]
@BigDataDaddy This makes sense (to include ACM trust keychain in JRE packaged in installer).
Two questions:
- Driver version update. As Redshift drivers aren't in any public Maven repository DBeaver uses direct download links and can't get the most recent driver version automatically. I wondering is there any way to automate this.
- Is there any doc which describes how/where to get trustchain, how to put it in JRE?
