### ISSUE TITLE
Migrate on Eclipse Oxygen

### ISSUE THREAD

**Issue by serge-rider** [serge-rider/dbeaver#2204]
We need to migrate on Eclipse Oxygen platform ASAP. 
Besides other things Neon doesn't support Java 9 (#2203)

**Comment by michelemauro** [comment]
I can report that on Oxygen there seem to be some strange behaviour opening the SQL Editor (sometimes Eclipse signals "Illegal Thread Access" or something in this line) but if I can grab hold of an editor window, everything seems well usable; with "everything" I mean normal SQL editing with Postgres connections, copy/paste from the data grid, and things like that.
Since I have parallel Neon (and an aging Mars) installations, I can do a little betatesting if you want.
Thank you for your great work.

**Comment by serge-rider** [comment]
@michelemauro Thank you!
We going to include Oxygen migration in the nearest release (4.2.2, will happen this Monday). So far I didn't find any blocker issues with Oxygen. If you'll be able to reproduce this problem with SQL Editor - please post error/debug log.
