### ISSUE TITLE
"Anonymous SQL parameters" not working for me

### ISSUE THREAD

**Issue by antonwierenga** [serge-rider/dbeaver#2229]
If I check "Anonymous SQL parameters" I get a prompted for the parameter values but upon execution a NullPointerException is thrown:

<img width="496" alt="screen shot 2017-09-29 at 07 51 57" src="https://user-images.githubusercontent.com/14827290/31002656-4566e1d4-a4ec-11e7-9249-1415688095cc.png">
<img width="483" alt="screen shot 2017-09-29 at 07 51 35" src="https://user-images.githubusercontent.com/14827290/31002657-4567d724-a4ec-11e7-93f1-b5d3a5fa5db6.png">

I am using DBeaver 4.2.1 on OSX 10.12.6 executing the statement on a Postgres 9.6.2.7 database.

EDIT: I also get the NullPointerException when using named parameters (e.g. "select * from dual where 1 = :param")

**Comment by serge-rider** [comment]
Can't reproduce that.
Please post error stacktrace (you can get it in Error Log view - just double click on error).

BTW NullPointerException in empty parameter value binding was fixed in #2190 - although it doesn't look like exactly the same case.
However you could check how it works in 4.2.2 (release on Oct 1st).

**Comment by antonwierenga** [comment]
Here you go:

**Comment by serge-rider** [comment]
Please check this in 4.2.2

**Comment by antonwierenga** [comment]
This now works in 4.2.2. Thanks.
