### ISSUE TITLE
DBeaver setting Result Sets -> Queries -> Use fetch-size has no effect

### ISSUE THREAD

**Issue by pdanie** [serge-rider/dbeaver#2275]
Beaver - **Version 4.2.2 CE**
DBeaver JDBC driver: **MS SQL Server - jTDS or Microsoft**
Operating System: **Windows 7 / Windows 8.1**

Even if I have the setting **Result Sets** -> **Queries** -> **Use fetch-size** unchecked, the _DBeaver_ reads **200** (the default **ResultSet fetch size**) rows at a time.

Only way I have found to have DBeaver read all rows in one go, is to set **Result Sets** -> **Queries** -> **ResultSet fetch size** to **0**.

**Comment by serge-rider** [comment]
Yes, to remove fetch size limitation you should change value 200 to 0 (you can do this directly in the main toolbar).

This pref option name (Use fetch-size) is a bit confusing (or not just a bit). 
I'll rename it because it affects internal JDBC  API thing which says nothing to regular users. And shouldn't be changed unless you are driver developer or something.
