### ISSUE TITLE
PostgreSQL how to work with multiple DB from one connection?

### ISSUE THREAD

**Issue by aviskase** [serge-rider/dbeaver#232]
Hello. I'm not very proficient with DBs, just using for work. Sorry that can't give any technical details.
 
Before 3.6 I used to check all available DBs on the server in pgadmin and then connect in dbeaver to the correct one.

pgadmin --- with these parameters I could see *all schemes* and execute queries on their tables:
* maintenance db: postgres
* login/password: postgres

For example, I need DB named "db1" (where all data are stored within "db1sm" scheme). Before 3.6 my connection in dbeaver would be:
* db: db1
* login/password: db1_rw

Now in 3.6 I assumed the behavior would be similar to pgadmin, and used its parameters (postgres). I can see now all DBs on the server, but when I want to look at schemes/tables for "db1" I get: `org.jkiss.dbeaver.DBException: DBException: Can't access non-default database` . 
OKAY. So I click "Set Active". But nevertheless I can't see the most important scheme of DB --- "db1sm". I can see it only if I connect with login/password for this DB. But then, I can't use the same connection to work with other DBs --- their lists of schemes all shows "db1sm" instead of their own.
![219](https://cloud.githubusercontent.com/assets/3819473/13291509/35c94ae8-db42-11e5-9d51-0bc3735b5680.png)

My point:
1) Is it normal that within one connection I can work only with one DB? Because "Set active" deactivates previously active DB. 
2) For all main schemes within DBs we have corresponding users. In pgadmin I can connect under "postgres" and do anything without restriction. In dbeaver3.6 to see the scheme in question I must connect by the scheme user. So to work with DBs I forced to created multiple connections again, like in previous dbeaver version.

**Comment by serge-rider** [comment]
Multi-database access is not yet supported in DBeaver. You can access only the default database (the one specified in the connection properties).
This is pretty complicated issue because PostgreSQL requires separate network connection for each database. Multi-database feature is tracked in #34.

**Comment by emmanueltouzery** [comment]
I don't know if this bug should be closed: if I have several databases on one server (which is normal), I still can work only one one DB at a time on a server, unless I'm mistaken? That's a limitation many (most?) other database tools don't have, so I think a bug should be kept open on that topic? I'm using 3.7.1 and still seeing this behavior.

**Comment by serge-rider** [comment]
Since DBeaver 3.6 you can switch active PostgreSQL database ("Set Active" in context menu).
But this action will disconnect from current database and connect to a new one.
It is a really frustrating feature. In PG different databases requires different physical connection. This means different transaction contexts, different security, everything. It is not a logical thing like in MySQL.
So if you need to work with multiple PG databases simultaneously then you need to create multiple connections. At the moment it is the only solution.

**Comment by emmanueltouzery** [comment]
but how can I do that in the GUI of dbeaver? create multiple connections I mean? Cannot dbeaver create the connections "behind my back" so I don't notice?

**Comment by serge-rider** [comment]
Just make multiple connections (in Database Navigator view) with the same server address but different database names. You may copy/paste connections to simplify the process.

**Comment by Reziana** [comment]
HI how are you? is in dbBeaver an options to make join querys between two databases?
for example

select * from database1.SaleInvoce as s
left join database2.SalesInvoiceDTL as dtl on s.sInvoiceID=dtl.sInvoiceID

or something similar?

**Comment by jgomo3** [comment]
~Feature Request~

I don't think anymore that this feature makes sense.

The equivalent in Postgres is the Schemas. Independently of DBeaver, one can't cross tables in different databases using simple queries, and connections are one per database.

It is a semantic issue. You just have to think on schemas instead of databases when working with Postgres, and BTW, that is the original intention of SQL.

**Comment by matisidler** [comment]
feature request
