### ISSUE TITLE
"java.lang.NullPointerException" when trying to insert multiple rows in an Oracle Connection

### ISSUE THREAD

**Issue by oscarmex** [serge-rider/dbeaver#2354]
The application throws a "java.lang.NullPointerException" when you try to insert two or more rows at the same time. After clicking ok, cancelling the operation and refreshing the data, you can notice that the first row is inserted, but the others are ignored and their data is lost.
![java lang nullpointerexception](https://user-images.githubusercontent.com/19717413/31684350-14892f74-b345-11e7-86e1-0f56fde715a8.PNG)

**Comment by serge-rider** [comment]
Please post error stacktrace (you can get it in Error Log view, main menu Window->Show view).
Also please provide steps to reproduce.

**Comment by oscarmex** [comment]
Step 1.- Open the "Data" tab on any table
Step 2.- Add two or more rows and insert valid data
Step 3.- Press Ctrl+S (save)

[log.log](https://github.com/serge-rider/dbeaver/files/1392402/log.log)

**Comment by serge-rider** [comment]
Thanks for details.
This error happens in Oracle JDBC driver. I can't reproduce this - most likely because of different driver version.

Error happens when DBeaver tries to read auto-generated column values (even if there are no auto-generated columns). I'll add a workaround to query executor so any error in keys reading won't break original query execution.

Workaround: try to use different Oracle JDBC driver version.

**Comment by oscarmex** [comment]
Thank you for your awesome work Serge! Be well and take care :)
