### ISSUE TITLE
Paste SQL from Java (or other) code?

### ISSUE THREAD

**Issue by bjorntj** [serge-rider/dbeaver#240]
When developing one often need to copy some sql statements from the code to run in the SQL editor. The problem is that these statements often includes characters like " and + that need to removed before one can run the statement.
Would be a nice feature..

**Comment by carlosjrcabello** [comment]
I believe the simplest way it will do the inverse of Eclispse's past literal:

![screen169](https://cloud.githubusercontent.com/assets/637767/13433230/b3ed381e-dfaf-11e5-8c3d-32ce3d079b7b.png)

So, when some sql command is pasted in editor, it can be ~normalized~ and applying a SQL Format on it (if necessary).

**Comment by codebling** [comment]
Hm...Would be a great feature but this might be hard to implement. Any ideas on how?  

@carlosjrcabello you're right, but it's harder going the reverse direction. Eclipse knows that you are in a string and doesn't care what's inside the data, simply splits it at 80 characters (or however many) and wraps it using Java's String concatenation operators. But going the other way is harder. Since DBeaver is also a standalone application, you could be pasting in from PHP with the `.` concatenation operator. 

_Maybe_ we could have a "paste from special" operation with a different hotkey which would try a "best guess" for removing these with a regex. I wonder how effective a simple naive regex would be...

**Comment by carlosjrcabello** [comment]
@codebling, you're right. 

I believe that using ER could be simpler than the instance that I was thought.

**Comment by serge-rider** [comment]
I like this feature but yes, it is not so easy to do.
Potentially it could be done as as a Paste handler (automatically determine that string contains source code from some programming language). This is a preferred way. Or as a separate command (if auto will be too complicated).
Fortunately there are no too many different languages with different syntaxes (not counting exotic ones). So 2-3 different heuristics should work..

**Comment by stepjacky** [comment]
@serge-rider  anything else, the code can be run as a syntax corrected java string

**Comment by serge-rider** [comment]
For now it'll work for Java, C, C++, C# and other languages with similar syntax.
![sql-from-source-config](https://cloud.githubusercontent.com/assets/6398845/13906279/bcb77598-eee3-11e5-8292-7fb50267470c.png)

**Comment by serge-rider** [comment]
For now algorithm  is very simple. But works.
Further improvement should be tracked in different issues.

**Comment by gillesB** [comment]
Hint for people who come from search engines (like me) because the feature stopped working:

It seems that in the Update to 23.0.2 `Extract SQL from source code` moved to another preference page and must be activated again.

![grafik](https://user-images.githubusercontent.com/1679281/233021167-fd28a235-161d-47fd-8222-7b3ce79065f3.png)
