### ISSUE TITLE
Symantec Endpoint Security alert

### ISSUE THREAD

**Issue by guinuxbr** [serge-rider/dbeaver#2441]
Symantec Endpoint Security remove my download alerting a threat. Here goes the log. 
As I read this statement **"All Windows/MacOS binaries are signed with Symantec Code Sign certificates (confirmed by Microsoft and Apple)."** at https://dbeaver.jkiss.org/download/, I think that you should check whats happening. Thanks in advance!

>  Filename:
> dbeaver-ce-4.2.4-x86_64-setup.exe
> Threat name: WS.Reputation.1Full Path: C:\dbeaver-ce-4.2.4-x86_64-setup.exe
> On computers as of 
> 30/10/2017 at 11:44:37
> Last Used 
> 30/10/2017 at 11:46:37
> Startup Item 
> No
> Launched 
> No
> Threat type: Insight Network Threat. There are many indications that this file is untrustworthy and therefore not safe
> 
> dbeaver-ce-4.2.4-x86_64-setup.exe Threat name: WS.Reputation.1
> Locate
> 
> Very Few Users
> Fewer than 5 users in the Symantec Community have used this file.
> 
> Very New
> This file was released less than 1 week  ago.
> 
> Medium
> This file risk is medium.
> 
> Source: External Media
> 
> Source File:
> dbeaver-ce-4.2.4-x86_64-setup.exe
> 
> File Actions
> 
> File: C:\dbeaver-ce-4.2.4-x86_64-setup.exe Removed
> 
> File Thumbprint - SHA:
> 1bf939fc5d7ab5e036d0ca805986cef2cfccfecd27e30d657448799224864bbf
> File Thumbprint - MD5:
> 56568072146d4dab2f7c77371868d7cf
>

**Comment by serge-rider** [comment]
In DBeaver 4.2.4 we've changed our code sign certificates to Rider Soft (as said in release announcements: https://dbeaver.jkiss.org/2017/10/29/dbeaver-4-2-4/).
Symantec End Point protection/Norton Antivirus detects it as "WS/Reputation.1" (https://www.symantec.com/security_response/writeup.jsp?docid=2010-051308-1854-99)
This means that this certificate isn't trusted enough because it is brand new (today is the first day of its usage). Some time should pass (week or two) before this certificate will be fully trusted by 3rd party anti-virus software.

Workaround: disable Symantec End Point Protection/Norton Antivirus before installing DBeaver.
We'll contact Symantec support for faster resolution of this problem.

**Comment by rythym05** [comment]
Another workaround for Symantec -
Change the level under Download Insight to 1. This will allow file download

![image](https://user-images.githubusercontent.com/29409893/32191538-b1da2976-bd6e-11e7-9c3d-8d06860f4e57.png)

**Comment by guinuxbr** [comment]
Ok, thanks for the info and congrats for this amazing software!
