### ISSUE TITLE
Hot key operation wants confirmation

### ISSUE THREAD

**Issue by offstate** [serge-rider/dbeaver#2466]
I set hot key Ctrl-E for Delete Line operation. After last app update the operation was duplicated by Ctrl-D and binding Ctrl-E was duplicated by some operation. 
I removed all conflicts but when I press the keys, I receive confirmation window in bottom right corner of the screen.

![default](https://user-images.githubusercontent.com/16996529/32304061-34aa12ee-bfb8-11e7-8870-eb39ff5885cf.png)

![default](https://user-images.githubusercontent.com/16996529/32304159-e9a585f2-bfb8-11e7-9b9c-bd3bf751387b.png)

**Comment by serge-rider** [comment]
<kbd>CTRL+E</kbd> is the default for editor switch. I removed it, right?
Anyhow this looks like some Eclipse bug.
Sometimes it can be resolved by application restart.

**Comment by offstate** [comment]
Restart doesn't help. 
Here is all my keys [keys.csv.txt](https://github.com/serge-rider/dbeaver/files/1439637/keys.csv.txt)

**Comment by serge-rider** [comment]
Looks like there were some conflicts with DBeaver shortcuts.
I've fixed a couple of shortcut contexts.
Try in the next version but first reset workspace settings (delete workbench.xmi following https://github.com/serge-rider/dbeaver/wiki/Reset-workspace doc).

Please reopen if this issue is still there.
