### ISSUE TITLE
Can't execute parallel queries in different tabs

### ISSUE THREAD

**Issue by antimirov** [serge-rider/dbeaver#2504]
Dear @serge-rider 

I'm running DBeaver 4.2.4 with PostgreSQL drive 42.1.4

When I execute a long query in one tab, say CREATE INDEX, I can't execute anything else anywhere in the dbeaver. When I open a new tab, I write a simple query, 'SELECT * FROM customers LIMIT 1' and this query is simply put to the 'Backround Tasks' queue. As soon as my CREATE INDEX finished (50 minutes), I get an immediate result from customers query, it takes ~1 ms.

I also tried Ctrl-\, Ctrl-Alt-X- no success. Found an issue similar to mine — #1551.

Additionally, when I press 'Cancel' button on those queries, they become gray and text says 'Cancelled', while 'Execute query - 123s' continues to run.

![dbeaver_bug](https://user-images.githubusercontent.com/68257/32652125-9201c706-c603-11e7-809a-22e846517f0e.png)

**Comment by serge-rider** [comment]
This is because of PostgreSQL network protocol. It doesn't support parallel query execution.
Workaround: enable "connection per editor" option:
![image](https://user-images.githubusercontent.com/6398845/32691626-b8ff9702-c71b-11e7-82b3-786dd7ebcdc5.png)
Now open multiple SQL editors. 
You can execute simultaneous queries in different editors.

**Comment by antimirov** [comment]
Thanks, it helped. Interestingly, this checkbox only worked when I closed my editors and opened new ones.

**Comment by rdp** [comment]
Has this config option moved or is it still there?
