### ISSUE TITLE
MS SQL 2008R2 tables view problem

### ISSUE THREAD

**Issue by infectormp** [serge-rider/dbeaver#283]
**3.6.2**
I setup connection to SQL server over jtd and Microsoft JDBC but in both cases i can't see tables in db, i see only roles or users. I doing something wrong?

![image](https://cloud.githubusercontent.com/assets/9958813/13768981/ec167420-ea8c-11e5-9c54-0dd5b4851728.png)

**Comment by serge-rider** [comment]
It is a standard behavior. Tables are inside roles (schemas).
I agree, this might be not very convenient for SQL Server because of it's specific metadata structure. But this is a default UI for all drivers based on Generic extension.
We have plans to make MSSQL/Sybase extension with different metadata representation but I can't say when exactly it will be ready.
