### ISSUE TITLE
Enable "commit/rollback" only if the action is possible

### ISSUE THREAD

**Issue by petrus0x13** [serge-rider/dbeaver#346]
Buttons "commit" and "rollback" should be only enabled, if particular action is really possible. It will help to determine, whether the user have any uncommited changes or not.

**Comment by operationgamma** [comment]
Tricky to do as some dbms vendors have operations where a commit (for example) is implied and you'd have to have good knowledge of them in order to not leave the commit/rollback buttons enabled when they wouldn't do anything.. for example:

------

-- Run these statements with auto-commit off one by one
CREATE TABLE test(id numeric);

INSERT INTO test SELECT 1 FROM dual;

ALTER TABLE test ADD blah varchar2(256);

-- Click on rollback at this point

-- Now run this
SELECT * FROM test;

-- Only run this is you want to clean up at the end - be careful in case you already had a table called 'test' in your system !
DROP TABLE test;

------

At the point of issuing the rollback, you could be led to believe that it would do something and should have been enabled, but in Oracle the above would do nothing and the subsequent select would return a single row with the value '1' in it.

So there was already an implied commit from the DDL (but this may not be true of all DBMS or all versions or even of all DDL) - quite tricky to know the actual state all the time.
