### ISSUE TITLE
PL/SQL DECLARE blocks parse support

### ISSUE THREAD

**Issue by marco-sanjuan** [serge-rider/dbeaver#445]
Hi again :)

I'm trying to execute a PL/SQL script but script executor is throwing a unexpected error.

The test script is this (extracted from oracle site)
DECLARE
  l_message  VARCHAR2 (100) := 'Hello World!';
BEGIN
  DBMS_OUTPUT.put_line (l_message);
END;

The result is:
![image](https://cloud.githubusercontent.com/assets/4165141/15263222/4e597e3e-1968-11e6-9263-4b3b85ddb685.png)

The same block runs fine on toad and sqldeveloper.

Thanks in advance!

**Comment by serge-rider** [comment]
The real problem is the same as in #418.
DBeaver doesn't yet support PL/SQL syntax (DECLARE and block terminator \ in particular).
I'll mark this issue as feature request. But don't expect fast resolution, that's an old and tough task.

Standard workaround is to select your SQL and execute it as a single statement (ctrl+enter).

**Comment by marco-sanjuan** [comment]
Ok, i'll watch both issues to be noticed, thanks.

**Comment by serge-rider** [comment]
DECLARE clause evaluation will be added in 3.7.1

**Comment by marco-sanjuan** [comment]
Wow great news! So then pl/sql will be full supported?

**Comment by serge-rider** [comment]
Not fully supported but at least PL/SQL blocks processing should be ok.
