### ISSUE TITLE
Auto Save SQL Editor

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#491]
Recently had the power go out and lost all of my unsaved sql editor tabs. (I have also lost my sql editor tabs in the past when my computer crashed & auto updated over night).

Can you provide an option that auto saves all open tabs every x minutes?
Can you provide an option that also saves the open tab whenever you run a query?

**Comment by serge-rider** [comment]
I don't really like auto-save feature (it can be harmful in general).
Moreover auto-save of database editors (like table editor) will be a disaster.

But saving SQL editor on query execution looks like a good idea. I'll add extra option (disabled by default).

**Comment by r-richmond** [comment]
awesome, I think saving sql editor on query execution is enough to solve my pain point and prevent most future data loses.

**Comment by carlosjrcabello** [comment]
I can help testing it. Really nice feature!

**Comment by serge-rider** [comment]
You can test it in EA version

**Comment by carlosjrcabello** [comment]
I've tested with **dbeaver-ee-3.6.9-x86_64-setup.exe** binary, and this feature works perfectly (as the picture below):

![screen227](https://cloud.githubusercontent.com/assets/637767/15709286/546fbd76-27da-11e6-9a19-1c949d0e3b85.png)

So, I had to check those options to allow auto save, and, based in problems that I got since oldest versions, when I executed some giant sql and editor sometimes freezes or crashes, I think those option, or at least, _'Auto save on query execution'_ comes enabled by default, and this one always triggered before execution.

What do you think about it?

However, this is a awesome feature.
