### ISSUE TITLE
Problems with postgresql sequences

### ISSUE THREAD

**Issue by gianpy** [serge-rider/dbeaver#503]
Sequences name are not recognized for postgresql if you try to call a sequence number (eg: select nextval('seq_xxx')) you receive a 42P01 error "relation seq_xxx don't exist"

**Comment by serge-rider** [comment]
Can't reproduce.
Are you sure that sequence is visible in your current search_path?

**Comment by gianpy** [comment]
yes, my schema is in my search_path ed is different of public. schema qualified "myschema.mysequence" work right but "mysequence" is not recognized whithout schema name.

**Comment by serge-rider** [comment]
I don't think I can fix this because it happens in PostgreSQL. 
If sequence was declared in a schema which presents in search_path (in terms of DBeaver you have to set this schema active) then this sequence must be visible/accessible. And there is no difference between sequences and other metadata objects.
If you have any thoughts why this is a DBeaver bug - please add a comment and I'll reopen this issue.
