### ISSUE TITLE
Connection: field "Host" can contain spaces but probably should not

### ISSUE THREAD

**Issue by lospejos** [serge-rider/dbeaver#506]
When creating new connection (f.e. PostgreSQL, but I assume this is true for other connection types), when pasting or entering text into "Host" field, it allows spaces (among other invalid symbols). This could lead to "connection error". User assumes that entered, f,e. "myhost.com", but actually field contains value " myhost.com" (note the leading space!).
I suggest trim data after pasting / editing (control focus lose), or, at least, display some warning (underscore with red line, mark as yellow bulb or something other). This is of course valid only if my suggestion that "Host" value cannot contain spaces etc is true. 
At least you could display host value in qouted / doubleqouted when displaying an exception. F.e.:
Exception text:  java.net.UnknownHostException: "  myhost.com" to display user a real host value that was used to connect.
DBeaver Enterprise 3.6.9 on Windows 10 x86_64, Java build 1.8.0_92-b14.

**Comment by serge-rider** [comment]
Agreed.

**Comment by adojaan** [comment]
The same problem appears with connections settings under Network->SSH Tunnel Settings. If Host/IP contains a space (for example in the end) due to careless paste it will result a Java connection error "Can't initialize tunnel, Cannot establish tunnel java.net.UnknownHostException:IP". trim() should be applied to this field as well or error message should display a space (for example, with IP quoted). (affected versions 6.0.0 .. 6.0.5)

**Comment by strangedev** [comment]
Commenting, because I'm experiencing this Issue again on version 6.2.2.201910121132, specifically in the SSH-tunnel configuration tab when editing connection properties. Possible regression?

System information:
Operating System: Manjaro Linux 
KDE Plasma Version: 5.17.2
KDE Frameworks Version: 5.63.0
Qt Version: 5.13.1
Kernel Version: 5.3.7-2-MANJARO
OS Type: 64-bit
Processors: 4 × Intel® Core™ i7-5600U CPU @ 2.60GHz
Memory: 7,7 GiB of RAM


Operating System: Manjaro Linux 
KDE Plasma Version: 5.17.2
KDE Frameworks Version: 5.63.0
Qt Version: 5.13.1
Kernel Version: 5.3.7-2-MANJARO
OS Type: 64-bit
Processors: 4 × Intel® Core™ i7-5600U CPU @ 2.60GHz
Memory: 7,7 GiB of RAM

**Comment by r3m4k3** [comment]
Why is it closed? This issue still occurs.
