### ISSUE TITLE
Row count missing

### ISSUE THREAD

**Issue by alexpetralia** [serge-rider/dbeaver#514]
I searched the forums but haven't found an answer for this. When I do queries on tables whose size exceeds the fetch count (eg. 1000), the row count of the results are not returned. For example, if I run a SELECT query returning 4000 rows, 1000 will display but there will be no indication the result size is 4000. I have 'Show row count for tables' checked off. Is there something else I'm missing?

Version: 3.6.9
Database: Postgres 9.3

**Comment by serge-rider** [comment]
DBeaver doesn't calculate actual row count on each select (at least because it may take a lot of time in case of big tables/complex queries).
You can turn on table row count reading in preferences (thus you will see total row count in table properties).
Generally if you see that DBeaver read exactly the same amount of rows as set in fetch size then you may assume that there are more rows. Also there are two extra actions in the results toolbar - "read next segment" and "read all rows". If these actions are enabled then you see only part of data.

**Comment by alexpetralia** [comment]
I couldn't find those options.. just to confirm, there's no "row count" possibility like there is in pgAdmin? If there is, which options should I have selected/unselected?

**Comment by serge-rider** [comment]
Not sure about pgAdmin, however you can enable row count calculation in Preferences:
![metadata_pref](https://cloud.githubusercontent.com/assets/6398845/15910278/d5dd6dce-2dd2-11e6-9c76-8ab679a3a9c9.png)

Then you can see row count in table properties:

![table_props](https://cloud.githubusercontent.com/assets/6398845/15910353/230b3d74-2dd3-11e6-964c-b63b6fa899a9.png)

Also you can see it in Properties view:

![props_view](https://cloud.githubusercontent.com/assets/6398845/15910411/5d22f20e-2dd3-11e6-9ad7-6725a0078dbb.png)
