### ISSUE TITLE
Password retained when "Save password" is unchecked

### ISSUE THREAD

**Issue by wskb** [serge-rider/dbeaver#518]
Steps to reproduce:

1. Create a connection without a password
2. Connect using connection; provide password; ensure that "Save password" is unchecked
3. Disconnect
4. Connect again - the password dialog is displayed, but the password field is-non empty. Clicking "OK" will allow re-connection without re-entering password.

Workaround: exit and reopen DBeaver.

**Comment by serge-rider** [comment]
Agreed.

**Comment by jheerTBG** [comment]
This issue has not been completely fixed. The password will no longer show up in the dialog, but if you go back into your "Edit Connections" you will see the password field is populated. If you then check the "Save Password Locally" checkbox under general section and then select test connection, you will connect without a prompt. This means that the password is still being saved locally, and looking at the commit, all that's happening is that you're preventing the saved password from being used in the prompt. We have been looking at our DB editor options, and DBeaver is off the table because we cannot have production DB passwords saved locally like this.

**Comment by jheerTBG** [comment]
I'll create a new issue for this.
