### ISSUE TITLE
UI Bug / Improvement Request: Import data Dialog Box

### ISSUE THREAD

**Issue by r-richmond** [serge-rider/dbeaver#595]
When I import data from another table the records processed message flashes too quickly to be read.

Can you break out the ui on that show it shows records processed and then next line has executing statement...  or something else you deem appropriate. 

Basically I'd like to be able to read the message.

![record_progress_flashes_to_fast](https://cloud.githubusercontent.com/assets/9246654/16824683/9b4ca16e-4922-11e6-823f-6683cc9fd178.gif)

**Comment by carlosjrcabello** [comment]
What do you think about database messages about import statements ?

**Comment by r-richmond** [comment]
I'm not sure I understand what you mean.

**Comment by serge-rider** [comment]
It is a bug in progress monitor, will be fixed in the next version. Thanks for report.

But I can't show statement text because:
- It can be too long (sometimes it takes hundreds of Kb and just printing it slows UI dramatically)
- Statement execution happens too often (thousands times per second) and also slows UI

**Comment by r-richmond** [comment]
@serge-rider  yea that makes sense when I said "executing statement" i literally just meant the text "executing statements..." or something like that.
