### ISSUE TITLE
Postgresql JSONB - Pretty print

### ISSUE THREAD

**Issue by loskultos** [serge-rider/dbeaver#605]
It would be a nice feature for a future verson of dbeaver if jsonb columns could be pretty printed, at least in the edit cell view. With Postgres 9.5 there has been introduced the jsonb_pretty function that could be useful here.

Maybe there is also a more database agnostic and more common solution to pretty print jsons, e.g. by using some library etc.

**Comment by lacanoid** [comment]
Perhaps some of the code used for displaying JSON databases (eg. mongo) can be adapted for this?

**Comment by serge-rider** [comment]
Yeah, I'm thinking about that..

**Comment by serge-rider** [comment]
#711 is about the same but more general, I'll close this one as duplicate.

**Comment by firehooper** [comment]
@serge-rider I am using EE 4.0.4 .  How do you pretty print postgresql jsonb fields?

**Comment by lacanoid** [comment]
Pretty printing would help a lot, since JSONB is now all squished into one line, which makes it a lot harder to edit. Perhaps a dedicated editor for the values (along the lines of current text, binary and xml editor), which automatically beautifies values (that would be OK for JSON vs. say XML) would be appropriate? Or just adding "beautify" to the menu, below "word wrap"...

**Comment by lacanoid** [comment]
Having a beautifier would almost entirely eliminate the need to have a specialized JSON editor, as mentioned above. In fact, editing beautified JSON as text is often easier than using specialized JSON editing UI.

**Comment by serge-rider** [comment]
Please create another feature request for JSON beautifier.

**Comment by firehooper** [comment]
Sorry I was thinking this was already in there after this issue.  Thanks for the great tool.  Here is the new issue: https://github.com/serge-rider/dbeaver/issues/1531
