### ISSUE TITLE
SQL error 42601 when explain plan a sql on GreenPlum DB

### ISSUE THREAD

**Issue by stevenluan07** [serge-rider/dbeaver#638]
Every SQL meet this problem. such as `SELECT * FROM pg_stat_user_tables;`

error msg is:

`SQL 42601: ERROR syntax error at or near "FORMAT" position 10`

**Comment by serge-rider** [comment]
DBeaver doesn't even have preconfigured GreenPlum DB driver. And it doesn't support explain plan for (that's for sure).
What makes you think it can do it?

**Comment by r-richmond** [comment]
@stevenluan07 

just run `explain select * from pg_stat_user_tables;` from the standard editor.

that works although I've reproduced your issue of using control-shift-e on the query.

If you're like me its because you are using the postgres connector for the greenplum db. When using control-shift-e it runs `EXPLAIN (FORMAT XML, ANALYSE) select *
from pg_stat_user_tables` which errors out on greenplum but runs fine on postgres. 

@serge-rider Greenplum is based off of Postgres so maybe you want to just clone the postgres one and tweak this feature to get a greenplum connector. But I leave that up to you.

**Comment by serge-rider** [comment]
I suspected something like that.
In that case yes, GreenPlum DB has to have it's own extension based on PG.
One may create a feature request but honestly I've never touched this thing.

**Comment by stevenluan07** [comment]
You r all right about it. The command <explain select * from pg_stat_user_tables;> worked fine. 
Thanks a lot.
