### ISSUE TITLE
Add tables to include filter on right click

### ISSUE THREAD

**Issue by your-mirror** [serge-rider/dbeaver#662]
It will be great if I can add tables to not only exclude filter, but to include filter too. 

For example, I selected 4-5 tables and add them to include filter, so I see only them. So this option is available when include filter is empty. Try to imagine what I should do to get similar result through filters dialog.

**Comment by serge-rider** [comment]
I don't want to add yet another context menu item (like "Filter everything but selection") because context menu is already quite heavy.
Do you have any thoughts how to add this feature in UI?

**Comment by majkinetor** [comment]
No specific new UI is required. Just extended the current UI to have combobox with set names as described at #580. 

Then, replace Filter table with Filter context menu which looks like this:

Filters
- Filter in
- Filter out
- Select filter set:
  - My set 1
  - My set 2

Alternativelly, you could change the filtering dialog not to contain the listview but basic multiline text with 1 filter item per line. Then you can filter something out, and if you want it in just copy paste it to different field. It is way more managable like that TBH, particularly since you can't quickly delete filters now (you need to click each item and click remove). Activation of the set could also be done there by simply selecting one from the combo box. This way no new context menu item is added.

**Question**: What about specifying regex here or at least globs? like `v*` to select all views etc. I thought this was already like that but I can't make it work now.

**Comment by serge-rider** [comment]
Yeah, that could work.

In regards to regex matcher - for now you can use SQL masks (% and _).

**Comment by majkinetor** [comment]
Thanks serge, I documented it [here](https://github.com/serge-rider/dbeaver/wiki/Projects). I had images prepared but couldn't commit them.

**Comment by serge-rider** [comment]
This feature doesn't cover #580 but context menu redesign will make it easier to support named filters.
