### ISSUE TITLE
Bind parameter Cancel button

### ISSUE THREAD

**Issue by adamitj** [serge-rider/dbeaver#664]
-Happens with All RDBMS
-All DBeaver builds

When running a big SQL statement with lots of bind parameters (or arguments), let's say, 50 or more like I do, if for some reason I want to cancel the SQL execution I need to press the Cancel Button in the "Bind Parameter" window 51 times (the number of parameters and one more time)

The cancel button should cancel the execution immediatelly, without cancel every single parameter. 

It is possible to have this feature?

**Comment by adamitj** [comment]
Oh, BTW, the same applies to the OK Button...

**Comment by serge-rider** [comment]
Thanks for report.

Workaround in 3.7.2: just click anywhere in dialog area to make editor to loose focus. Then you can press OK or Cancel.

**Comment by masebu** [comment]
Hi,

since this change was made (3.7.3), I find the bind dialog's behavior unsettling.
If I change a bind's value then click directly on OK to run the statement [or use <TAB> to go to the OK button rather than <Enter>], it doesn't take my change, it runs with the old remembered value.

I'd expect that:
* if I click Cancel, the statement doesn't run and the changed binds are reverted to their old values.
* conversely, if I click OK, the statement runs with the new values (even if each value has not been validated separately).

What do you think ?

Furthermore, I notice this morning on 3.7.4 that values tend to get mixed up when using <TAB> to switch between values.
For instance, I start with binds recname = KS%SCHED% and rectype = 0, both remembered from a previous execution.
<img width="329" alt="dbeaver_bind_01_initialstate" src="https://cloud.githubusercontent.com/assets/19706602/18432711/e6df651c-78e3-11e6-98af-14ac25ec697c.png">

I change recname to KS%SCHED%STP and use <TAB> to go to rectype. rectype is also changed to 
KS%SCHED%STP without me doing anything.
<img width="329" alt="dbeaver_bind_02_changeontab" src="https://cloud.githubusercontent.com/assets/19706602/18432720/efb16942-78e3-11e6-9674-34ec903cf62a.png">

I have to click on the rectype bind line to have it into focus again. I change rectype back to 0 and either use <TAB> to go to the ok button or <Enter> to validate the value > recname bind is also changed to 0.
<img width="329" alt="dbeaver_bind_03_changeonenter" src="https://cloud.githubusercontent.com/assets/19706602/18432731/fba06c12-78e3-11e6-81c4-17f1b20da797.png">

**Comment by serge-rider** [comment]
Yes, tab navigation is broken. Thanks for report.

Workaround: use `Enter` key to set variable value and switch to the next one.
