### ISSUE TITLE
auto complete incorrectly word to uppercases even within quotes

### ISSUE THREAD

**Issue by zinking** [serge-rider/dbeaver#710]
while the uppercase of keywords like `where` is very neat.  I actually don't want columns within quotes like "column1" to be automatically uppercased to "COLUMN1" because it results in incorrect column name.

**Comment by serge-rider** [comment]
DBeaver doesn't convert identifiers case. Most likely your identifier conflicts with reserved keyword (and this explains why it should be quoted).
DBeaver shouldn't convert keyword case if keyword is in quotes. This is a bug, it will be fixed in the next version, thanks for report.

Workaround: disable keywords case conversion (Preferences->General->Editors->SQL Editor->Auto format).
