### ISSUE TITLE
Bind variables not found

### ISSUE THREAD

**Issue by dipasi** [serge-rider/dbeaver#713]
Hello gurus

I have the following query running in DBeaver 3.7.3:

`select
(V.FTP_Dollars_Base*-1*(366/:Curr_Days)/S.Average_Balance)*100
[...]
from
[...]
where
F.Operative_Situation_Date > :Prior_Month
[...]
and a.fecdata = :Curr_Month
[...]`

When running the query, DBeaver prompts a popup window for Bind Variables with only Curr_Month and Prior_Month, while Curr_Days variable is missing. After giving values to these two, the query fails with the following error message "Can not bind statement parameter".

Is this a limitation in the tool? something that could be improved maybe?

Thanks!

**Comment by serge-rider** [comment]
By default DBeaver assumes that identifiers `:name` are dynamic parameters (this is true for most of standard databases).
You can disable dynamic parameters in preferences (Preferences->General->Editors->SQL Editor->SQL Processing->Parameters).

**Comment by dipasi** [comment]
Hi

No, I don't want to disable dynamic parameters, I want DBeaver to prompt all of them.

Note that in my example above, I have three dynamic parameters:
  :Curr_Days
  :Curr_Month
  :Prev_Month

But when I run the query, DBeaver only asks for values for the last two of them.

Trust is clearer now.

**Comment by serge-rider** [comment]
I see.
The problem is in leading slash character.
If colon symbol is preceded with slash, back slash, colon or question mark then it is not evaluated as parameter. Maybe slash shouldn't be in this list.
Honestly I don't remember why this rule exists. Most likely it is somehow related to expressions or escaping.

Workaround: insert space character before colon.

**Comment by dipasi** [comment]
Thanks, that made the trick!!!
