### ISSUE TITLE
Please provide a way to set the resultset display locale independent of local machine settings

### ISSUE THREAD

**Issue by someotherdataguy** [serge-rider/dbeaver#718]
For example, I would prefer to see all datetimes formatted in the timezone of my choice (note that this formatting should take into account the actual value to do the conversion correctly). 

I would also like to be able to specify that NO conversion should be applied, ie, equivalent to asking the database to do the formatting in the sql statement. 

Eg, select text(myDateTimeWithTimeZoneInfoColName) from ....

Using my database impl shows me an ISO formatted string that provides the stored date, time and timezone info in that value, without any client side conversions.

This would be very helpful in determining if values are correctly being stored and used by applications.

Many thanks

**Comment by serge-rider** [comment]
You can change datetime formatting in preferences.
Regarding "native" formatting - there is no such thing (at least in JDBC). Every database client may represent timestamps differently just because there is no default pattern.

JDBC doesn't provide ability to perform server-side timestamp formatting. So the only way to get server-side formatting is to execute something like 
select text(myDateTimeWithTimeZoneInfoColName) from ...

**Comment by someotherdataguy** [comment]
Aha - thanks for the clarification.

If I want the timezone in the timestamp format, how should I specify the pattern?

yyyy-MM-dd HH:mm:ss????

Many thanks

**Comment by serge-rider** [comment]
`z` or `Z`
Note: most JDBC drivers looses timezone information on client side (so you always will see client time zone).
