### ISSUE TITLE
Foreign Key View

### ISSUE THREAD

**Issue by IS-smcleod** [serge-rider/dbeaver#76]
A view/mode for the data tab that resolves foreign keys to values like the dictionary in the editor.  Probably off by default if it affects performance.

**Comment by AlphaBravo777** [comment]
Have this feature been implemented? How do I activate it if it has. I have been looking everywhere for it.

**Comment by svagier** [comment]
Any update on this? How to see e.g. name value of FK instead of id?

**Comment by uslss** [comment]
Seems that value [panel](https://github.com/dbeaver/dbeaver/wiki/Panels) can be used

**Comment by svagier** [comment]
> Seems that value [panel](https://github.com/dbeaver/dbeaver/wiki/Panels) can be used

Unfortunately, that's not what I mean. As presented on the screenshot, Panels (on the right) allow me to see 'Descriptions' of fields from the referenced table (_trackers_actiontype_), and highlight the value in referenced table when field with Foreign Key is clicked (_action_type_id_). In other words, to see what given Foreign Key in column _action_type_id_ means, I have to click it and then look to the right.

I would like to have these 'Descriptions' in column _action_type_id_  instead of numbers (ids). Or be able to add an extra column which contains these 'Descriptions'. Then each row in my table _trackers_issuemeta_ would have an extra column, which would say what is the 'Description' of the _trackers_actiontype_ field it references. This would be much more readable and efficient than what I show on the screen.

Is there any way to do that? Or maybe the 'Panels' functionality should be used in another way?
![image](https://user-images.githubusercontent.com/48804774/101936156-7d8c6c80-3be0-11eb-95b0-a074159d518e.png)

**Comment by technodrome** [comment]
Why has this ticket been just silently closed without any comment or status? This would be very nice to have. It's 2020, I don't want to open 5 panels just to see the resolved FK value. This could definitely be shown inline.

For a currently fetched subset of queries on a decently fast PC, this would be surely doable.

@serge-rider Any comments?

**Comment by svagier** [comment]
@technodrome I've found a workaround which is simply creating a SQL query in SQL Editor. However I also would like to have this feature built-in.

**Comment by AlphaBravo777** [comment]
After following this issue for over two years, and still using DBeaver daily, I can say that it is still the only thing I am missing, up to the point that every now and again I think about moving to another DB manager just for this issue. 

It comes down to the following: when I look at my tables, I can easily click on a record to see what the foreign key value is, but if I want to see the foreign key value for the record below it (or any other record for that matter), I have to then click on that one again (depending on how many FK's there are) to see it value. And so as I look over the data I have to click on every FK to see its value. Instead of being just able to look at the table with all the values filled in, and scrolling up and down seeing everything I need to see all at once.

**Comment by d-01** [comment]
@AlphaBravo777, did you find an alternative DB manager with drop-down support for FKs?

**Comment by AlphaBravo777** [comment]
No, at the moment I am still using dbeaver. It is good on what I ise it for
other wise, so am I living with this inconvenience for the moment.
