### ISSUE TITLE
Feature Request - Ask for script name before save

### ISSUE THREAD

**Issue by adamitj** [serge-rider/dbeaver#786]
It would be amazing if right after press CTRL+S or point to menu "File" - "Save" for the first time DBeaver opens a window asking the name of script.

An easy option to rename the scripts is also needed, like a submenu entry when right click at tab name of the script.

I work with a lot of scripts every day, and managing from "Script" to "Script-125" is very difficult. Sometimes I create more than 3 scripts at time and is hard to rename them in scripts view after.

**Comment by carlosjrcabello** [comment]
Hi Tiago,

It's sounds interesting, current mode of save and auto save are fine,
however I'm with you about rename scripts.

A not intrusive way should be rename current script through double click on
his tab, what do you think about it @serge?

**Comment by serge-rider** [comment]
In 3.7.5 I've added new easy way to rename scripts - just press `F2` when SQL editor is active.

I see two problems in asking script name before save:
- Script file already exists at that moment
- It is annoying ("I just want to execute a query and I have no idea how to name this file")

**Comment by carlosjrcabello** [comment]
I didn't know it, very nice serge!

**Comment by adamitj** [comment]
Oh! Upgraded right now. Didn't know it too, F2 should do the trick. Thank you @serge-rider !

**Comment by assyrus-favolo** [comment]
Hello, I do agree with the possible problems that it might cause to the user, but I still believe it would be good to have it as an option that the user can consciously enable.  
I find myself quickly saving via <kbd>Ctrl</kbd> + <kbd>s</kbd> so that I don't inadvertently lose my modifications, but forget that the command will save the script as `Script-<number>.sql`, which becomes a problem later when I need to sort through my old scripts to find something I need again, because most were left with a generic auto-generated name. Forcing myself to name them would help me keep everything organized
