### ISSUE TITLE
New Vertica 7.x driver

### ISSUE THREAD

**Issue by StefanoRomano71** [serge-rider/dbeaver#820]
Hello,

It would be great if you add in the rope the version 7.X of the vertica drivers because there are possible connection problem between 6.x drivers and 7.x servers.

You can find them here https://my.vertica.com/download/vertica/client-drivers/ while an article useful for this issue is this: https://community.dev.hpe.com/t5/Vertica-Forum/Occassional-Error-during-COPY-statement-using-Python-Pyodbc/td-p/205089 which does not talk about the dbeaver usage but we have between some connections.

Please consider this as very useful for us.

Thanks in advance.

SR

**Comment by serge-rider** [comment]
That's not so easy.
1. As far as I know there is backward compatibility problem with JDBC drivers (i.e. you can't use new driver with old database - at least this problem was there for 5 and 6 versions).
2. Vertica drivers have proprietary license which do not allow drivers redistribution. Similarly to Oracle and DB2 drivers.

So for now the best solution is to download appropriate drivers from Vertica website.

**Comment by StefanoRomano71** [comment]
Thanks a lot.
We will put it manually as the driver.

SR
