### ISSUE TITLE
Syntax Highlighting not working with big sql files

### ISSUE THREAD

**Issue by trivago-izelenov** [serge-rider/dbeaver#886]
this is not working properly since v 3.7.4 or v 3.7.5 
* i have a dump sql script file with 23000 rows
* the sql highlighting stops working after i restart dbeaver for this file
* highlighting still works for smaller amount of rows also after restart

**Comment by serge-rider** [comment]
This was made on purpose. Syntax highlighting disabled for files bigger than 1Mb. 
Otherwise it consumes to much memory/CPU (UI freezes all the time).
We going to improve SQL parser after version 3.8.

**Comment by Eddie-Hartman** [comment]
@serge-rider Sorry for reviving this thread. If there is a better way to ask these kinds of questions let me know.
Was the above 'issue' ever tackled in a later version?
I'm opening a file 10Mb in size and notice some strange behavior.

For example, if I open the file, it won't do syntax highlighting. If I copy and paste it in chunks to a new script in dbeaver, it will highlight though. (This makes sense due to your above comment)

The weird part comes in where if I try to just run the script, I'll get an error. If I copy and past it out in sections to a new script though, I can run it. (The scripts are identical)
If I save the script I copy-pasted to, the syntax highlighting will go away and I can no longer run the script again.
This is the error I get: `SQL Error [105] [S0001]: Unclosed quotation mark after the character string 'ERROR I1: Failed Dropping Existing Table. [DROP TABLE PON_GLOB_VAR]'.` but I know that it's actually not an issue because again I can copy-paste the script in parts and then it will run.
This is all in SQL Server.

**Comment by rdp** [comment]
Noticed today if I have a single line of 100K characters SQL editor drags to a standstill...very slow...FWIW :)
