### ISSUE TITLE
ADD Support for multiple instances of DBeaver

### ISSUE THREAD

**Issue by allanlaal** [serge-rider/dbeaver#890]
it would be most helpful if I could start multiple instances of DBeaver (with the same config including database navigator) to manage multiple databases/projects simultaneously without getting into tab hell

**Comment by serge-rider** [comment]
It is not possible to open multiple DBeaver instances on a single workspace.

But you can open multiple DBeaver windows: main menu Window->Open in New Window.

**Comment by allanlaal** [comment]
is it possible to add this behaviour as a parameter to the dbeaver binary so that I can launch a new instance via a shortcut on my desktop.

use case:
I have 13 virtual desktops and I would have to find the one that has a DBeaver instance in order to launch a new instance and then move it to the desktop I was working on

**Comment by serge-rider** [comment]
Hmm, no, I don't think that it is possible to control this from command line.
If you will open new window then all windows will be reopened next time you will start DBeaver.
All these limitations comes from Eclipse framework, this will require too much effort to fix this :(

I think that the only workaround for you issues would be to create multiple workspaces (and run different instances of DBeaver with different `-data <path>` parameters.
They won't share connections but you can copy .dbeaver-data-sources.xml from one workspace to another.

**Comment by allanlaal** [comment]
thanks, that's sufficient for now :)

**Comment by allanlaal** [comment]
@serge-rider would it be possible to add a command line option that executes Database -> Disconnect all after a new instance is started? This would somewhat alleviate the danger caused by DBeaver loading a older random session every time I run a new instance (I have ~4..5 instances running at different times)

**Comment by serge-rider** [comment]
You could create a feature request. Although it doesn't look as a frequently used feature..

**Comment by allanlaal** [comment]
@serge-rider you mean most people don't use multiple instances of DBeaver?

**Comment by serge-rider** [comment]
I mean command line options + disconnect all.
Just though - I could add command line option which will execute ANY DBeaver command (passed along with this option). This could be an interesting feature..

**Comment by allanlaal** [comment]
@serge-rider for a start, I would happy with command line options to disconnect all and close all, so I get a fresh empty DBeaver every time I push the DBeaver button on my keyboard.. yes, it has its own button ;)

**Comment by serge-rider** [comment]
Please create a separate feature request for command line options feature.

**Comment by allanlaal** [comment]
for Googlers (and me again in 6 years :laughing:):

https://github.com/dbeaver/dbeaver/wiki/Command-Line

**Comment by Binly42** [comment]
for Googlers (a linux `.desktop` workflow example):


suppose I am using `Flatpak DBeaver` and I have a `~/proj1/DBeaverData/workspace6/` :
- create a `~/proj1/DBeaver.desktop` like:
  ```properties
  [Desktop Entry]
  Version=1.0
  Type=Application
  Terminal=false
  Name=DBeaver CE (proj1)
  Comment=DBeaver Workspace of proj1
  Icon=io.dbeaver.DBeaverCommunity
  StartupWMClass=DBeaver
  StartupNotify=true
  Categories=IDE;Development;
  Keywords=Database;SQL;IDE;JDBC;ODBC;MySQL;PostgreSQL;
  GenericName=Database Manager
  MimeType=application/sql;
  Exec=sh -c "/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=/app/dbeaver/dbeaver io.dbeaver.DBeaverCommunity -data $(dirname '%k')/DBeaverData/workspace6"
  X-Flatpak=io.dbeaver.DBeaverCommunity
  ```

  if do not care about the `Name` nor `Comment` (for note, distinguish, etc), might be okay to directly copy-and-paste this `.desktop` file into those workspaces location of different projects.

  NOTE: this `.desktop` was based on the one generated from flatpak, hence maybe many items could be reduced ? ~

  NOTE: the `$(dirname '%k')` is a workaround (because [a `dex` bug](https://github.com/jceb/dex/issues/37)) , and would be errored by `desktop-file-validate`. however we would not install the `.desktop`, because that would not work well with our relative path param .

- [use `dex` to make `.desktop`files executable](https://github.com/cheesecakeufo/komorebi/issues/40#issuecomment-434880427)
